### ISSUE TITLE
auto connect to  the last paired device function?

### ISSUE THREAD

**Issue by xfdr0805** [pschatzmann/ESP32-A2DP#1]
automatically connect to the last paired devices function ? 
good job,thanks a lot

**Comment by JohnyMielony** [comment]
Just implemented such function in my fork of this library. Go ahead look at the code.

**Comment by pschatzmann** [comment]
Cool! Would you be willing to submit a pull request ?

**Comment by JohnyMielony** [comment]
I did pull request. Please check if everything is ok.

**Comment by pschatzmann** [comment]
Cool Thanks a lot!

**Comment by pschatzmann** [comment]
Hmm. I just checked... I don't see any open Pull Requests

**Comment by JohnyMielony** [comment]
There it is: https://github.com/pschatzmann/ESP32-A2DP/pull/18

**Comment by pschatzmann** [comment]
Perfect! 
Thanks a lot for your help.

**Comment by pschatzmann** [comment]
Merged to master
