### ISSUE TITLE
Example with confirm_pin_code()

### ISSUE THREAD

**Issue by essenius** [pschatzmann/ESP32-A2DP#101]
I'm trying to get the pin code mechanism to work using activate_pin_code(true) in setup() and confirm_pin_code() in loop() when a button is pressed. The phone gives the pin challenge and the esp32 calls confirm_pin_code() but the pairing fails. Could you provide a simple example that should work?

What I did: 
```
#include "BluetoothA2DPSink.h"

const int BUTTON = 0;
const int BUTTON_PRESSED = 0;

BluetoothA2DPSink a2dp_sink;

void setup() {
  a2dp_sink.activate_pin_code(true);
  a2dp_sink.start("Receiver");  
}

void loop() {
  if (digitalRead(BUTTON) == BUTTON_PRESSED) {
    a2dp_sink.confirm_pin_code();
  }
 delay(1000);
}
```

**Comment by essenius** [comment]
Yes, I did, and that's what I tried to implement, But apparently I am missing a step.

**Comment by pschatzmann** [comment]
I have commited some corrections and I have also added [an example](https://github.com/pschatzmann/ESP32-A2DP/blob/main/examples/bt_music_receiver_simple_with_pin/bt_music_receiver_simple_with_pin.ino
). It is using sensitive touch on pin 13.
But I would expect that your example is working as well...

**Comment by shakisha** [comment]
is it possible an example using the boot button (which seems GPIO 0)? 

I have done many trials but I'm unable to make it work.
