### ISSUE TITLE
Play Position

### ISSUE THREAD

**Issue by RustColeone** [pschatzmann/ESP32-A2DP#102]
Is it possible to get the progress of the music currently playing?

**Comment by pschatzmann** [comment]
If you get the most recent version you can define the avrc information that are requested: e.g. just call set_avrc_metadata_attribut_mask(ESP_AVRC_MD_ATTR_TITLE | ESP_AVRC_MD_ATTR_ARTIST | ESP_AVRC_MD_ATTR_ALBUM | ESP_AVRC_MD_ATTR_TRACK_NUM | ESP_AVRC_MD_ATTR_NUM_TRACKS | ESP_AVRC_MD_ATTR_GENRE | AVRC_MEDIA_ATTR_ID_PLAYING_TIME);
before you call start();

However I never tried this out myself.

**Comment by RustColeone** [comment]
Thanks, although I was not able to get it to work, so far I was only able to get the total time with ESP_AVRC_MD_ATTR_PLAYING_TIME, but AVRC_MEDIA_ATTR_ID_PLAYING_TIME would not compile and complain that it is not defined. No luck with getting the current position. I don't know how but I think the Bluetooth on cars is able to get the progress bar, which is why I wanted to do the same. I tried using a timer, but would instantly break when I fast forward.
