### ISSUE TITLE
Source Connection Issues

### ISSUE THREAD

**Issue by tartunian** [pschatzmann/ESP32-A2DP#112]
I just updated from v1.0.0 to the latest and I can't seem to get the A2DPSource to connect to a sink (laptop, headphones). Using the example 'bt_music_sender', I changed "RadioPlayer" to the name of my headphones but will not connect like it did with v1.0.0 (I tried two sets of headphones and also my laptop).

However, I can manually get my laptop to connect to ESP_A2DP_SRC and open the connection with the Bluetooth Audio Receiver app but the ESP disconnects almost immediately. b0:05:94:eb:52:70 is my laptop address but I am not sure yet what 50:f4:eb:5b:a3:2a belongs to.

Below is my debug connection output.

`[D][BluetoothA2DPSource.cpp:586] process_user_state_callbacks(): process_user_state_callbacks ESP_A2D_CONNECTION_STATE_EVT: Connecting

[D][BluetoothA2DPSource.cpp:250] bt_app_work_dispatch(): bt_app_work_dispatch event 0x0, param len 12
[D][BluetoothA2DPSource.cpp:301] bt_app_task_handler(): bt_app_task_handler, sig 0x1, 0x0
[D][BluetoothA2DPSource.cpp:854] bt_av_hdl_avrc_ct_evt(): bt_av_hdl_avrc_ct_evt evt 0
[I][BluetoothA2DPSource.cpp:860] bt_av_hdl_avrc_ct_evt(): AVRC conn_state evt: state 1, [b0:05:94:eb:52:70]
[D][BluetoothA2DPSource.cpp:250] bt_app_work_dispatch(): bt_app_work_dispatch event 0x0, param len 16
[D][BluetoothA2DPSource.cpp:301] bt_app_task_handler(): bt_app_task_handler, sig 0x1, 0x0
[I][BluetoothA2DPSource.cpp:610] bt_app_av_sm_hdlr(): bt_app_av_sm_hdlr state 3, evt 0x0
[D][BluetoothA2DPSource.cpp:578] process_user_state_callbacks(): process_user_state_callbacks
[D][BluetoothA2DPSource.cpp:250] bt_app_work_dispatch(): bt_app_work_dispatch event 0x5, param len 12
[D][BluetoothA2DPSource.cpp:586] process_user_state_callbacks(): process_user_state_callbacks ESP_A2D_CONNECTION_STATE_EVT: Connected
[D][BluetoothA2DPSource.cpp:301] bt_app_task_handler(): bt_app_task_handler, sig 0x1, 0x5
[D][BluetoothA2DPSource.cpp:854] bt_av_hdl_avrc_ct_evt(): bt_av_hdl_avrc_ct_evt evt 5
[I][BluetoothA2DPSource.cpp:891] bt_av_hdl_avrc_ct_evt(): AVRC remote features
[D][BluetoothA2DPSource.cpp:250] bt_app_work_dispatch(): bt_app_work_dispatch event 0xff00, param len 0
[D][BluetoothA2DPSource.cpp:301] bt_app_task_handler(): bt_app_task_handler, sig 0x1, 0xff00
[I][BluetoothA2DPSource.cpp:610] bt_app_av_sm_hdlr(): bt_app_av_sm_hdlr state 3, evt 0xff00
[D][BluetoothA2DPSource.cpp:578] process_user_state_callbacks(): process_user_state_callbacks
[I][BluetoothA2DPSource.cpp:646] bt_app_av_state_unconnected(): a2dp connecting to peer: 50:f4:eb:5b:a3:2a
[D][BluetoothA2DPSource.cpp:250] bt_app_work_dispatch(): bt_app_work_dispatch event 0x0, param len 16
[D][BluetoothA2DPSource.cpp:301] bt_app_task_handler(): bt_app_task_handler, sig 0x1, 0x0
[I][BluetoothA2DPSource.cpp:610] bt_app_av_sm_hdlr(): bt_app_av_sm_hdlr state 4, evt 0x0
[D][BluetoothA2DPSource.cpp:578] process_user_state_callbacks(): process_user_state_callbacks
[D][BluetoothA2DPSource.cpp:586] process_user_state_callbacks(): process_user_state_callbacks ESP_A2D_CONNECTION_STATE_EVT: Disconnected`

**Comment by pschatzmann** [comment]
I added some logic to automatically reconnect to the last successful address. You can switch this off by calling
```
a2dp_source.set_auto_reconnect(false) 
a2dp_source.start("RadioPlayer", get_data_channels);  
```

**Comment by pschatzmann** [comment]
I also just committed a change to store the last address for the sink and the source under different names...

**Comment by tartunian** [comment]
Thanks. This one got it working again:
```
a2dp_source.set_auto_reconnect(false); 
```
