### ISSUE TITLE
"Diacoverability" problem still occurs

### ISSUE THREAD

**Issue by Zaws44** [pschatzmann/ESP32-A2DP#144]
Problem descripted in closed issue :
https://github.com/pschatzmann/ESP32-A2DP/issues/110
still makes an error when compiling.

I've tried on Arduino 2.0 and 1.8.4  (same result) and library version 1.6 (1.5 works like a charm).

**Comment by pschatzmann** [comment]
I think you are not using the latest version of the library

**Comment by Zaws44** [comment]
My bad , I've downloaded zip from releases.
