### ISSUE TITLE
Any way to run BluetoothA2DPSink alongside BluetoothA2DPSource?

### ISSUE THREAD

**Issue by anisjonischkeit** [pschatzmann/ESP32-A2DP#158]
I'm hoping to receive Audio using the sink, do some modifications and then pass the output to the source. Is this possible? I've got both examples working individually but for some reason when I join them together things stop working:

```
void setup(){
  a2dp_source.start("Anis", get_data_channels);  
  a2dp_sink.start("Receiver");  
}
```

If anyone has tried this before, would love to hear from you

**Comment by anisjonischkeit** [comment]
Looks like this could be a limitation of the esp32/the fact it only has one radio (or at least the way in which they implement a2dp). If anyone knows anything different, do let me know though.

**Comment by pschatzmann** [comment]
That would be my understanding as well. You would need to connect 2 ESP32 via I2S - which seems to have it's challenges as well.
