### ISSUE TITLE
could it send audio to one device and receive data as slave from another ?

### ISSUE THREAD

**Issue by mikewong18** [pschatzmann/ESP32-A2DP#159]
I'm  trying to connect my esp32 to a bluetooth earphone and another esp32 using BluetoothSerial at the same time. Is it possible? 
```
BluetoothA2DPSource a2dp_source;
BluetoothSerial SerialBT;
void setup(){
a2dp_source.start("ULL Me-200"); 
  SerialBT.begin("ESP32Test");
}
```
a2dp works as normal but I can not connect to esp32 with any other devices' bluetooth.

**Comment by pschatzmann** [comment]
I don't think that this will work.

**Comment by zhubinsheng** [comment]
Really can't work？qaq
