### ISSUE TITLE
a2dp_source.set_auto_reconnect(false) doesn't work

### ISSUE THREAD

**Issue by FerFemNemBem** [pschatzmann/ESP32-A2DP#169]
Hi,
even if I set:
`a2dp_source.set_auto_reconnect(false);`
everytime I come back with the disconnected device or switch off/on Bluetooth at the device it immediatly reconnects.

From my understanding this should not be the case if "auto_reconnect" is set to false.
I'm missing something here or is "auto_reconnect" something different?

Best regards,
FFNB

**Comment by pschatzmann** [comment]
After you call a2dp_source.set_auto_reconnect(false); the a2dp_source does not try to reconnect. - However it might be that the corresponding sink has some reconnect functionality...

**Comment by FerFemNemBem** [comment]
This makes sense.
Thank you!
