### ISSUE TITLE
A2DP-source connection works with "WH1000X-M2" but not with "JBL Clip 3"

### ISSUE THREAD

**Issue by Chuck-2022** [pschatzmann/ESP32-A2DP#184]
I'm trying to set my ESP32-DEVKITC-32D to be a source for multiple speakers. I started by connecting only one at the time and I'm having trouble connecting my JBL Clip 3. I already tried a2dp_source.set_auto_reconnect(false) for preventing connecting to the last headphones but it's still doesn't connect. 
They both have the same bluetooth version and support A2DP.
What should I try?
Thank you!

**Comment by pschatzmann** [comment]
Try to set the debug mode to verbose. Maybe the log might indicate where something goes wrong...

**Comment by pschatzmann** [comment]
I just merged a correction which might help
