### ISSUE TITLE
Disable logs in serial monitor

### ISSUE THREAD

**Issue by JoaoPedroAssis** [pschatzmann/ESP32-A2DP#187]
Hi! I'm using this library to receive music in my esp32 board, and I'm using PlatformIO for development. I would like to know how can I disable all logs that are being printed on the serial monitor. It's just that the sink client logs so much stuff that I end up loosing my own logs. Thanks in advance!

**Comment by pschatzmann** [comment]
; None
build_flags = -DCORE_DEBUG_LEVEL=0

; Error
build_flags = -DCORE_DEBUG_LEVEL=1

; Warn
build_flags = -DCORE_DEBUG_LEVEL=2

; Info
build_flags = -DCORE_DEBUG_LEVEL=3

; Debug
build_flags = -DCORE_DEBUG_LEVEL=4

; Verbose
build_flags = -DCORE_DEBUG_LEVEL=5
