### ISSUE TITLE
how to stream live audio with bt_music_sender or bt_music_sender_write

### ISSUE THREAD

**Issue by Bollebie** [pschatzmann/ESP32-A2DP#20]
When i tested the original bt_music_sender_write with sloeber i had some problems.
i had to change:
extern const uint8_t StarWars10_raw[]; --> into extern const uint8_t StarWars30_raw[]; 
extern const unsigned int StarWars10_raw_len; --> into extern const unsigned int StarWars30_raw_len;

BluetoothA2DPSource a2dp_source;
//SoundData *data = new TwoChannelSoundData((Channels*)StarWars10_raw,StarWars10_raw_len/4);
SoundData *data = new OneChannelSoundData((int16_t*)StarWars30_raw, StarWars30_raw_len/2);

Now i get error --> code is to big

I had to downsize audio file to get it working.
Now i can send small audio file to BT-speaker with bt_music_sender_write.

the question is how to stream audio from input pin to my BT-speaker?

**Comment by veryalien** [comment]
To hear the streamed audio you just need to put the correct bluetooth speaker name in the a2dp_source.start call.
For example, my speaker is called M5_SPEAKER_T1 (which I can see as a bluetooth speaker on my smartphone), so I use a2dp_source.start("M5_SPEAKER_T1");
If you use the correct bluetooth speaker name, your ESP32 should connect to the speaker automatically and after a few seconds you should hear the audio.

**Comment by pschatzmann** [comment]
compile errors have been corrected
