### ISSUE TITLE
Is it possible only play BIP to Bluetooth speaker with esp32 without files? 

### ISSUE THREAD

**Issue by joroMaser** [pschatzmann/ESP32-A2DP#204]

**Comment by pschatzmann** [comment]
What is BIP ?

**Comment by joroMaser** [comment]
like 
https://www.youtube.com/watch?v=RPfCZhvj1Ng
I don't want to store mp3 files on esp32
@pschatzmann

**Comment by pschatzmann** [comment]
You mean beep(), 
So you obviously did not even look at the provided examples!

**Comment by pschatzmann** [comment]
Take a look at the https://github.com/pschatzmann/ESP32-A2DP/blob/main/examples/bt_music_sender/bt_music_sender.ino example. You can provide some generated values during a short period of time and after that just return 0
