### ISSUE TITLE
use this lib no voice output 

### ISSUE THREAD

**Issue by BruceAKABear** [pschatzmann/ESP32-A2DP#207]
when I upload this lib to my esp32 dev module,not voice output, I use pcm5102a to dec i2s ,this chip work very well . how can I use this lib in right way?

here is my code:
`
#include "BluetoothA2DPSink.h"

BluetoothA2DPSink a2dp_sink;

void setup()
{

  i2s_pin_config_t i2SPinConfig = { .bck_io_num = GPIO_NUM_27,
                                    .ws_io_num = GPIO_NUM_26,
                                    .data_out_num = GPIO_NUM_25,
                                    .data_in_num = I2S_PIN_NO_CHANGE
                                  };
  a2dp_sink.set_volume(30);
  a2dp_sink.set_pin_config(i2SPinConfig);
  a2dp_sink.start("MyMusic");
  Serial.begin(115200);
  Serial.println(a2dp_sink.get_volume());
}

void loop()
{
  delay(1000); // do nothing
}

`

**Comment by BruceAKABear** [comment]
> Did you read the Wiki - External-DAC ?

yes, and I use my DAC module in another project and it work good . and I redefine the i2s pin ,I think it well work but no output,so I dont konw what should I do net step

**Comment by pschatzmann** [comment]
Which I2S Module exactly do you have ?
Are you sure that your other project is not defining additional non I2S pins to feed the module ?

**Comment by BruceAKABear** [comment]
> Well, if you have defined the pins correctly it should work. Which I2S Module exactly do you have ? Are you sure that your other project is not defining additional non I2S pins to feed the module (e.g. for the XMT pin)? How did you test ? Maybe you just need to increase the volume on your phone ? Did you activate the logging and look at the log messages ?

I bulid a DAC module by myself ,it based on pcm5102a chip. and in order to use that module I hava handle other pin such as xmt in right way .
here is pin config and i2s config in my wifi audio project:

`
// i2s配置
i2s_config_t i2sConfig = { .mode = (i2s_mode_t)(I2S_MODE_MASTER | I2S_MODE_TX),
                           .sample_rate = 44100,
                           .bits_per_sample = I2S_BITS_PER_SAMPLE_16BIT,
                           .channel_format = I2S_CHANNEL_FMT_ONLY_LEFT,
                           .communication_format =
                             i2s_comm_format_t(I2S_COMM_FORMAT_I2S),
                           .intr_alloc_flags = ESP_INTR_FLAG_LEVEL1,
                           .dma_buf_count = 4,
                           .dma_buf_len = 512,
                           .use_apll = true,
                           .tx_desc_auto_clear = true,
                           .fixed_mclk = I2S_PIN_NO_CHANGE
                         };
// i2s pin配置
i2s_pin_config_t i2SPinConfig = { .bck_io_num = GPIO_NUM_27,
                                  .ws_io_num = GPIO_NUM_26,
                                  .data_out_num = GPIO_NUM_25,
                                  .data_in_num = I2S_PIN_NO_CHANGE
                                };
`
I upload my wifi audio firamewate to my esp32 to test the module work or not, the volume  in my cellphone is 100%


here is my log:

`
ELF file SHA256: 0000000000000000

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1240
load:0x40078000,len:13012
load:0x40080400,len:3648
entry 0x400805f8
[    32][I][BluetoothA2DPSink.cpp:1052] set_volume(): set_volume 30
[    33][I][BluetoothA2DPSink.cpp:1202] volume_set_by_local_host(): Volume is set locally to: 23
[    36][I][BluetoothA2DPCommon.cpp:207] log_free_heap(): Available Heap: 200492
[    43][I][BluetoothA2DPSink.cpp:136] start(): Device name will be set to 'MyMusic'
[    51][I][BluetoothA2DPSink.cpp:184] init_i2s(): init_i2s
[    56][I][BluetoothA2DPSink.cpp:186] init_i2s(): init_i2s is_i2s_output
[   151][I][BluetoothA2DPSink.cpp:263] init_bluetooth(): controller initialized
[   478][I][BluetoothA2DPSink.cpp:272] init_bluetooth(): bluedroid initialized
[   548][I][BluetoothA2DPSink.cpp:281] init_bluetooth(): bluedroid enabled
[   548][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[   553][I][BluetoothA2DPCommon.cpp:241] set_scan_mode_connectable(): set_scan_mode_connectable true
[   561][I][BluetoothA[  Sin1][pp:360] app_task_handler(): app_taskBlantoor, APP_SIG_WORK_DIAPATSins.g: :475]   5_1apI]alluetco():2DPent:.10
p:5[   a74]dl_[Bd_etoo[   586][I][BluetoothA2DPSink.cpp:475] app_gap_callback(): event: 10
30
[   589][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[   591][I][BluetoothA2DPSink.cpp:638] handle_connection_state(): partner address: 14:c6:97:aa:64:0a
[   600][I][BluetoothA2DPSink.cpp:646] handle_connection_state(): A2DP connection state: Connecting, [14:c6:97:aa:64:0a]
[   611][I][BluetoothA2DPSink.cpp:718] handle_connection_state(): ESP_A2D_CONNECTION_STATE_CONNECTING
[  2128][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[  2128][I][BluetoothA2DPSink.cpp:570] handle_audio_cfg(): a2dp audio_cfg_cb , codec type 0
[  2134][I][BluetoothA2DPSink.cpp:582] handle_audio_cfg(): a2dp audio_cfg_cb , sample_rate 44100
[  2143][I][BluetoothA2DPSink.cpp:593] handle_audio_cfg(): configure audio player 21-15-2-35

[  2151][I][BluetoothA2DPSink.cpp:599] handle_audio_cfg(): audio player configured, samplerate=44100
[  2178][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[  2178][I][BluetoothA2DPSink.cpp:638] handle_connection_state(): partner address: 14:c6:97:aa:64:0a
[  2185][I][BluetoothA2DPSink.cpp:646] handle_connection_state(): A2DP connection state: Connected, [14:c6:97:aa:64:0a]
[  2196][I][BluetoothA2DPSink.cpp:684] handle_connection_state(): ESP_A2D_CONNECTION_STATE_CONNECTED
[  2204][I][BluetoothA2DPCommon.cpp:241] set_scan_mode_connectable(): set_scan_mode_connectable false
[  2213][I][BluetoothA2DPSink.cpp:704] handle_connection_state(): i2s_start
[  2297][I][BluetoothA2DPSink.cpp:465] app_gap_callback(): ESP_BT_GAP_READ_REMOTE_NAME_EVT stat:0
[  2299][I][BluetoothA2DPSink.cpp:467] app_gap_callback(): ESP_BT_GAP_READ_REMOTE_NAME_EVT remote name:OPPO Find X
[  2520][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[  2520][I][BluetoothA2DPSink.cpp:760] av_hdl_avrc_evt(): AVRC conn_state evt: state 1, [14:c6:97:aa:64:0a]
[  2528][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[  2537][I][BluetoothA2DPSink.cpp:1237] av_hdl_avrc_tg_evt(): AVRC conn_state evt: state 1, [14:c6:97:aa:64:0a]
[  2547][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[  2556][I][BluetoothA2DPSink.cpp:784] av_hdl_avrc_evt(): AVRC metadata rsp: attribute id 0x1, Run Free (feat. IVIE)
[  2566][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[  2576][I][BluetoothA2DPSink.cpp:784] av_hdl_avrc_evt(): AVRC metadata rsp: attribute id 0x2, Deep Chills/IVIE
[  2586][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[  2595][I][BluetoothA2DPSink.cpp:784] av_hdl_avrc_evt(): AVRC metadata rsp: attribute id 0x4, Run Free (feat. IVIE)
[  2605][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[  2614][I][BluetoothA2DPSink.cpp:784] av_hdl_avrc_evt(): AVRC metadata rsp: attribute id 0x8, 0
[  2623][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[  2632][I][BluetoothA2DPSink.cpp:784] av_hdl_avrc_evt(): AVRC metadata rsp: attribute id 0x10, 0
[  2641][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[  2650][I][BluetoothA2DPSink.cpp:784] av_hdl_avrc_evt(): AVRC metadata rsp: attribute id 0x20, 
[  2659][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[  2668][I][BluetoothA2DPSink.cpp:807] av_hdl_avrc_evt(): remote rn_cap: count 6, bitmask 0xe26
[  2712][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[  2712][I][BluetoothA2DPSink.cpp:784] av_hdl_avrc_evt(): AVRC metadata rsp: attribute id 0x1, Run Free (feat. IVIE)
[  2720][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[  2729][I][BluetoothA2DPSink.cpp:784] av_hdl_avrc_evt(): AVRC metadata rsp: attribute id 0x2, Deep Chills/IVIE
[  2739][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[  2749][I][BluetoothA2DPSink.cpp:784] av_hdl_avrc_evt(): AVRC metadata rsp: attribute id 0x4, Run Free (feat. IVIE)
[  2759][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[  2768][I][BluetoothA2DPSink.cpp:784] av_hdl_avrc_evt(): AVRC metadata rsp: attribute id 0x8, 0
[  2777][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[  2786][I][BluetoothA2DPSink.cpp:784] av_hdl_avrc_evt(): AVRC metadata rsp: attribute id 0x10, 0
[  2794][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[  2804][I][BluetoothA2DPSink.cpp:784] av_hdl_avrc_evt(): AVRC metadata rsp: attribute id 0x20, 
[  5380][I][BluetoothA2DPSink.cpp:475] app_gap_callback(): event: 13
[ 61728][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[ 61728][I][BluetoothA2DPSink.cpp:608] handle_audio_state(): A2DP audio state: Started
[ 61734][I][BluetoothA2DPSink.cpp:619] handle_audio_state(): i2s_start
[ 76741][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[ 76741][I][BluetoothA2DPSink.cpp:608] handle_audio_state(): A2DP audio state: Stopped
[ 76747][W][BluetoothA2DPSink.cpp:624] handle_audio_state(): i2s_stop
[ 76753][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[ 76762][I][BluetoothA2DPSink.cpp:638] handle_connection_state(): partner address: 14:c6:97:aa:64:0a
[ 76771][I][BluetoothA2DPSink.cpp:646] handle_connection_state(): A2DP connection state: Disconnected, [14:c6:97:aa:64:0a]
[ 76782][I][BluetoothA2DPSink.cpp:649] handle_connection_state(): ESP_A2D_CONNECTION_STATE_DISCONNECTED
[ 76791][I][BluetoothA2DPSink.cpp:660] handle_connection_state(): i2s_stop
[ 76798][I][BluetoothA2DPCommon.cpp:241] set_scan_mode_connectable(): set_scan_mode_connectable true
[ 76807][I][BluetoothA2DPSink.cpp:475] app_gap_callback(): event: 13
[ 80727][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[ 80728][I][BluetoothA2DPSink.cpp:760] av_hdl_avrc_evt(): AVRC conn_state evt: state 0, [00:00:00:00:00:00]
[ 80735][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[ 80744][I][BluetoothA2DPSink.cpp:1237] av_hdl_avrc_tg_evt(): AVRC conn_state evt: state 0, [00:00:00:00:00:00]
[ 88496][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[ 88496][I][BluetoothA2DPSink.cpp:638] handle_connection_state(): partner address: 14:c6:97:aa:64:0a
[ 88503][I][BluetoothA2DPSink.cpp:646] handle_connection_state(): A2DP connection state: Connecting, [14:c6:97:aa:64:0a]
[ 88514][I][BluetoothA2DPSink.cpp:718] handle_connection_state(): ESP_A2D_CONNECTION_STATE_CONNECTING
[ 88559][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[ 88560][I][BluetoothA2DPSink.cpp:570] handle_audio_cfg(): a2dp audio_cfg_cb , codec type 0
[ 88566][I][BluetoothA2DPSink.cpp:582] handle_audio_cfg(): a2dp audio_cfg_cb , sample_rate 44100
[ 88756][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[ 88756][I][BluetoothA2DPSink.cpp:638] handle_connection_state(): partner address: 14:c6:97:aa:64:0a
[ 88763][I][BluetoothA2DPSink.cpp:646] handle_connection_state(): A2DP connection state: Connected, [14:c6:97:aa:64:0a]
[ 88774][I][BluetoothA2DPSink.cpp:684] handle_connection_state(): ESP_A2D_CONNECTION_STATE_CONNECTED
[ 88782][I][BluetoothA2DPCommon.cpp:241] set_scan_mode_connectable(): set_scan_mode_connectable false
[ 88791][I][BluetoothA2DPSink.cpp:704] handle_connection_state(): i2s_start
[ 88805][I][BluetoothA2DPSink.cpp:475] app_gap_callback(): event: 13
[ 88815][I][BluetoothA2DPSink.cpp:475] app_gap_callback(): event: 13
[ 88844][I][BluetoothA2DPSink.cpp:465] app_gap_callback(): ESP_BT_GAP_READ_REMOTE_NAME_EVT stat:0
[ 88844][I][BluetoothA2DPSink.cpp:467] app_gap_callback(): ESP_BT_GAP_READ_REMOTE_NAME_EVT remote name:OPPO Find X
[ 89064][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[ 89065][I][BluetoothA2DPSink.cpp:760] av_hdl_avrc_evt(): AVRC conn_state evt: state 1, [14:c6:97:aa:64:0a]
[ 89072][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[ 89081][I][BluetoothA2DPSink.cpp:1237] av_hdl_avrc_tg_evt(): AVRC conn_state evt: state 1, [14:c6:97:aa:64:0a]
[ 89151][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[ 89152][I][BluetoothA2DPSink.cpp:807] av_hdl_avrc_evt(): remote rn_cap: count 6, bitmask 0xe26
[ 89193][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[ 89193][I][BluetoothA2DPSink.cpp:608] handle_audio_state(): A2DP audio state: Started
[ 89199][I][BluetoothA2DPSink.cpp:619] handle_audio_state(): i2s_start
[ 89222][I][BluetoothA2DPSink.cpp:475] app_gap_callback(): event: 13
[ 89319][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[ 89319][I][BluetoothA2DPSink.cpp:784] av_hdl_avrc_evt(): AVRC metadata rsp: attribute id 0x1, Run Free (feat. IVIE)
[ 89328][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[ 89337][I][BluetoothA2DPSink.cpp:784] av_hdl_avrc_evt(): AVRC metadata rsp: attribute id 0x2, Deep Chills/IVIE
[ 89347][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[ 89356][I][BluetoothA2DPSink.cpp:784] av_hdl_avrc_evt(): AVRC metadata rsp: attribute id 0x4, Run Free (feat. IVIE)
[ 89366][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[ 89375][I][BluetoothA2DPSink.cpp:784] av_hdl_avrc_evt(): AVRC metadata rsp: attribute id 0x8, 0
[ 89384][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[ 89393][I][BluetoothA2DPSink.cpp:784] av_hdl_avrc_evt(): AVRC metadata rsp: attribute id 0x10, 0
[ 89402][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[ 89411][I][BluetoothA2DPSink.cpp:784] av_hdl_avrc_evt(): AVRC metadata rsp: attribute id 0x20, 
[ 89420][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[ 89429][I][BluetoothA2DPSink.cpp:784] av_hdl_avrc_evt(): AVRC metadata rsp: attribute id 0x1, Run Free (feat. IVIE)
[ 89439][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[ 89448][I][BluetoothA2DPSink.cpp:784] av_hdl_avrc_evt(): AVRC metadata rsp: attribute id 0x2, Deep Chills/IVIE
[ 89458][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[ 89468][I][BluetoothA2DPSink.cpp:784] av_hdl_avrc_evt(): AVRC metadata rsp: attribute id 0x4, Run Free (feat. IVIE)
[ 89478][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[ 89487][I][BluetoothA2DPSink.cpp:784] av_hdl_avrc_evt(): AVRC metadata rsp: attribute id 0x8, 0
[ 89496][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[ 89505][I][BluetoothA2DPSink.cpp:784] av_hdl_avrc_evt(): AVRC metadata rsp: attribute id 0x10, 0
[ 89513][I][BluetoothA2DPSink.cpp:360] app_task_handler(): app_task_handler, APP_SIG_WORK_DISPATCH sig: 1
[ 89523][I][BluetoothA2DPSink.cpp:784] av_hdl_avrc_evt(): AVRC metadata rsp: attribute id 0x20, 

`

**Comment by pschatzmann** [comment]
When the phones sends the audio you should see the following log lines
12:33:24.545 -> [125087][D][BluetoothA2DPSink.cpp:936] audio_data_callback(): stream_reader
12:33:24.545 -> [125108][D][BluetoothA2DPSink.cpp:929] audio_data_callback(): audio_data_callback
12:33:24.545 -> [125110][D][BluetoothA2DPSink.cpp:936] audio_data_callback(): stream_reader
12:33:24.580 -> [125131][D][BluetoothA2DPSink.cpp:929] audio_data_callback(): audio_data_callback
12:33:24.580 -> [125132][D][BluetoothA2DPSink.cpp:936] audio_data_callback(): stream_reader
12:33:24.580 -> [125154][D][BluetoothA2DPSink.cpp:929] audio_data_callback(): audio_data_callback

I suggest to check and visualize the received audio data with the bt_music_receiver_datacallback.ino sketch in the Serial Plotter...

**Comment by BruceAKABear** [comment]
> When the phones sends the audio you should see the following log lines (with Log Level Verbose) 12:33:24.545 -> [125087][D][BluetoothA2DPSink.cpp:936] audio_data_callback(): stream_reader 12:33:24.545 -> [125108][D][BluetoothA2DPSink.cpp:929] audio_data_callback(): audio_data_callback 12:33:24.545 -> [125110][D][BluetoothA2DPSink.cpp:936] audio_data_callback(): stream_reader 12:33:24.580 -> [125131][D][BluetoothA2DPSink.cpp:929] audio_data_callback(): audio_data_callback 12:33:24.580 -> [125132][D][BluetoothA2DPSink.cpp:936] audio_data_callback(): stream_reader 12:33:24.580 -> [125154][D][BluetoothA2DPSink.cpp:929] audio_data_callback(): audio_data_callback
> 
> I suggest to check and visualize the received audio data with the bt_music_receiver_datacallback.ino sketch in the Serial Plotter...
> 
> This will help to identify if the issue in with A2DP or I2S.
> 
> ps. what is the reason why you used channel_format = I2S_CHANNEL_FMT_ONLY_LEFT in the other project ?

ok, my bad. I define a pin to control chip mute.the lib worked now
