### ISSUE TITLE
support esp32-a1s

### ISSUE THREAD

**Issue by 0neday** [pschatzmann/ESP32-A2DP#209]
esp32-a1s is powerful chip, https://docs.ai-thinker.com/en/esp32-a1s

**Comment by pschatzmann** [comment]
Just use my [arduino-audiokit ](https://github.com/pschatzmann/arduino-audiokit) best together with my [arduino-audio-tools](https://github.com/pschatzmann/arduino-audio-tools). You will find A2DP in the examples

**Comment by 0neday** [comment]
your [arduino-audio-tools](https://github.com/pschatzmann/arduino-audio-tools) , support [DLNA](https://github.com/espressif/esp-adf/blob/master/examples/advanced_examples/dlna/README.md) render ?
