### ISSUE TITLE
How to use 'esp_a2d_media_ctrl' command?

### ISSUE THREAD

**Issue by KIdon-Park** [pschatzmann/ESP32-A2DP#21]
Hi, Thank you very much for the work you made.

I use this library to use the BT speaker function, and I want to add some control functions.
I want to stop or restart music playing directly from the firmware.

I confirmed that esp_a2d_media_ctrl exists in esp_a2dp_api.h.
So, I was trying to use the function. When playing, enter the following command to stop
esp_a2d_media_ctrl(ESP_A2D_MEDIA_CTRL_SUSPEND)

In case of STOP or SUSPEND, execute the following to start playback.
esp_a2d_media_ctrl(ESP_A2D_MEDIA_CTRL_START)

Unfortunately, neither of these works.
Commands such as esp_bt_gap_set_scan_mode(ESP_BT_SCAN_MODE_CONNECTABLE) work.

Why can't command like play/pause music work? Is there any solution that you help me?

**Comment by pschatzmann** [comment]
Unfortunately I never tried to do this myself. 

Did you have a look at AVRCP API (https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/bluetooth/esp_avrc.html). My gut feeling is that you might be able to pause the sender with the esp_avrc_ct_send_passthrough_cmd() by using ESP_AVRC_PT_CMD_PAUSE .

If you just want to switch the sound on and off you could overwrite the audio_data_callback() method.

**Comment by KIdon-Park** [comment]
Thank you pschatzmann|
I will read the docu on that link. and try again. if I have any progress, will leave a message here.

**Comment by KIdon-Park** [comment]
Thank you. it's helpful advice.
I try to these commands today. And it works great.

if anyone wants to use this function as below.

1. PLAY
      esp_avrc_ct_send_passthrough_cmd(0, ESP_AVRC_PT_CMD_PLAY, ESP_AVRC_PT_CMD_STATE_PRESSED);
      esp_avrc_ct_send_passthrough_cmd(0, ESP_AVRC_PT_CMD_PLAY, ESP_AVRC_PT_CMD_STATE_RELEASED);
      
2. PAUSE
      esp_avrc_ct_send_passthrough_cmd(0, ESP_AVRC_PT_CMD_PAUSE, ESP_AVRC_PT_CMD_STATE_PRESSED);
      esp_avrc_ct_send_passthrough_cmd(0, ESP_AVRC_PT_CMD_PAUSE, ESP_AVRC_PT_CMD_STATE_RELEASED);
      
3. STOP
      esp_avrc_ct_send_passthrough_cmd(0, ESP_AVRC_PT_CMD_STOP, ESP_AVRC_PT_CMD_STATE_PRESSED);
      esp_avrc_ct_send_passthrough_cmd(0, ESP_AVRC_PT_CMD_STOP, ESP_AVRC_PT_CMD_STATE_RELEASED);
      
4. NEXT
      esp_avrc_ct_send_passthrough_cmd(0, ESP_AVRC_PT_CMD_FORWARD, ESP_AVRC_PT_CMD_STATE_PRESSED);
      esp_avrc_ct_send_passthrough_cmd(0, ESP_AVRC_PT_CMD_FORWARD, ESP_AVRC_PT_CMD_STATE_RELEASED);
      
5. PREV
      esp_avrc_ct_send_passthrough_cmd(0, ESP_AVRC_PT_CMD_BACKWARD, ESP_AVRC_PT_CMD_STATE_PRESSED);
      esp_avrc_ct_send_passthrough_cmd(0, ESP_AVRC_PT_CMD_BACKWARD, ESP_AVRC_PT_CMD_STATE_RELEASED);

**Comment by biglee991228** [comment]
@KIdon-Park @pschatzmann 
thanks a lot for your advice,I got it!

void loop() {
 a2dp_sink.set_AVRC_metadata(avrc_metadata_callback); 
 //a2dp_sink.set_stream_reader(stream_reader_callback);
 if(Serial.available()){
  //read until a terminator. after this point there should only be numbers
  command = Serial.readStringUntil('#');
  if(command.equals("play")){
   esp_avrc_ct_send_passthrough_cmd(0, ESP_AVRC_PT_CMD_PLAY, ESP_AVRC_PT_CMD_STATE_PRESSED);
   esp_avrc_ct_send_passthrough_cmd(0, ESP_AVRC_PT_CMD_PLAY, ESP_AVRC_PT_CMD_STATE_RELEASED);
   Serial.println("play");
    }
  if(command.equals("pause")){
   esp_avrc_ct_send_passthrough_cmd(0, ESP_AVRC_PT_CMD_PAUSE, ESP_AVRC_PT_CMD_STATE_PRESSED);
   esp_avrc_ct_send_passthrough_cmd(0, ESP_AVRC_PT_CMD_PAUSE, ESP_AVRC_PT_CMD_STATE_RELEASED);
   Serial.println("pause");
    }  
  if(command.equals("stop")){
   esp_avrc_ct_send_passthrough_cmd(0, ESP_AVRC_PT_CMD_STOP, ESP_AVRC_PT_CMD_STATE_PRESSED);
   esp_avrc_ct_send_passthrough_cmd(0, ESP_AVRC_PT_CMD_STOP, ESP_AVRC_PT_CMD_STATE_RELEASED);
   Serial.println("stop");
    }  
  if(command.equals("forward")){
   esp_avrc_ct_send_passthrough_cmd(0, ESP_AVRC_PT_CMD_FORWARD, ESP_AVRC_PT_CMD_STATE_PRESSED);
   esp_avrc_ct_send_passthrough_cmd(0, ESP_AVRC_PT_CMD_FORWARD, ESP_AVRC_PT_CMD_STATE_RELEASED);
   Serial.println("forward");
    }
   if(command.equals("backward")){
   esp_avrc_ct_send_passthrough_cmd(0, ESP_AVRC_PT_CMD_BACKWARD, ESP_AVRC_PT_CMD_STATE_PRESSED);
   esp_avrc_ct_send_passthrough_cmd(0, ESP_AVRC_PT_CMD_BACKWARD, ESP_AVRC_PT_CMD_STATE_RELEASED);
   Serial.println("backward");
    }
 }
}
my phone was controlled correctly!

**Comment by pschatzmann** [comment]
Cool - thanks for your feed back. 

Since this is so simple, I have finally decided to add this to my API as well...

**Comment by BR-Kacha** [comment]
@biglee991228

Can you help me to solve this?
Compilation error: 'class BluetoothA2DPSink' has no member named 'set_AVRC_metadata'

I am including "BluetoothA2DPSink.h" library.

**Comment by pschatzmann** [comment]
What do you expect to get if you add a non existing method ? 
I think the error message makes a lot of sense !

Please check the documentation for the available methods and their syntax. I guess you wanted to call set_avrc_metadata_callback
