### ISSUE TITLE
how set UDA1334A Breakout Board with LSB-justified 24 bits input 

### ISSUE THREAD

**Issue by 0neday** [pschatzmann/ESP32-A2DP#210]
I have check UDA1334A  pcb scheme [here ](https://cdn-learn.adafruit.com/assets/assets/000/048/419/original/adafruit_products_schem.png?1511325937), and found LSB-justified 24 bits input when sfor0 and sfor1 is HIGH. 
![微信截图_20220416100434.png](https://s2.loli.net/2022/04/16/JodstHzrBnVcvWS.png)

set 
```
.bits_per_sample = (i2s_bits_per_sample_t) 24,
.communication_format = (i2s_comm_format_t) (I2S_COMM_FORMAT_I2S | I2S_COMM_FORMAT_I2S_LSB | RIGHT_JUSTIFYING_MODE), 
```
it will be work fine?

**Comment by pschatzmann** [comment]
What exactly are you trying to do ? Is the [described settings](https://github.com/pschatzmann/ESP32-A2DP/wiki/External-DAC) not working ?

**Comment by 0neday** [comment]
thank you, just to test

**Comment by pschatzmann** [comment]
I don't think that you need to mess with any SFOR settings. 
Why don't you just set the i2s_config.bits_per_sample to 24 or 32 ?

**Comment by 0neday** [comment]
I set back to 16bit sample
