### ISSUE TITLE
Not working in windows 11

### ISSUE THREAD

**Issue by Daniel454fk** [pschatzmann/ESP32-A2DP#229]
hello i have a problem with windows 11, it connects, it detects as an audio device but in control panel in sound it says disconnected and no audio comes out, on a cell phone it works and , I am using it with internal dac

**Comment by clarkbremer** [comment]
Make sure you have disconnected the phone first.  It will only connect to one device at a time.  You can disconnect in software also, using `disconnect()`.

**Comment by pschatzmann** [comment]
It might also be related to https://github.com/pschatzmann/ESP32-A2DP/wiki/Auto-Reconnect

**Comment by Daniel454fk** [comment]
I'll try to do it and see if it works
