### ISSUE TITLE
Errors in bt_music_sender_write example

### ISSUE THREAD

**Issue by veryalien** [pschatzmann/ESP32-A2DP#23]
There seem to be a couple of errors in the bt_music_sender_write:

You define StarWars10_raw and StarWars10_raw_len in your sketch, but your example data is called StarWars30!

Please check your example data sample again. On my test system (M5Stack M5Paper and M5 Atom Echo) your original example data plays twice as fast as it should.

After following your instructions to create my own stereo 44100 16-bit PCM sample data (from a random star wars ringtone sample) in audacity and converting with xxd, my sample plays at the right speed as TwoChannelSoundData.

**Comment by pschatzmann** [comment]
I corrected the compile errors
