### ISSUE TITLE
Can't add anything to loop()

### ISSUE THREAD

**Issue by gmglickman** [pschatzmann/ESP32-A2DP#232]
I'm trying to expand the streaming example streams-url_mp3-i2s.ino to allow cycling between multiple URLs but the ESP32 becomes unresponsive to anything added to loop() once streaming starts. It won't allow polling a pushbutton in the loop(), for example, or toggling LED, or Serial.print. Nor does an interrupt work. What am I missing?

**Comment by pschatzmann** [comment]
This scenario is make available via the player, I suggest that you have a look at
https://github.com/pschatzmann/arduino-audio-tools/tree/main/examples/examples-player
