### ISSUE TITLE
can not return correct play_pos

### ISSUE THREAD

**Issue by biglee991228** [pschatzmann/ESP32-A2DP#236]
I wrote the follows in my loop(),but always returned 0 and Serialprint out.

uint32_t play_position = esp_avrc_ct_send_get_rn_capabilities_cmd(ESP_AVRC_RN_PLAY_POS_CHANGED);
Serial.println(play_position);
delay(1000);

I don't know why because I used new version 2.0.3

**Comment by pschatzmann** [comment]
A2DP methods are returning an esp_error_t so if you get 0 it means that the command was executed successfully. 

Result processing in A2DP is always done via the event handler.  If you check my code I am doing this call already both in the source and sink and the result should be available in s_avrc_peer_rn_cap.bits.

**Comment by biglee991228** [comment]
but how can I print out the "s_avrc_peer_rn_cap.bits"

**Comment by pschatzmann** [comment]
I have added the get_avrc_peer_rn_cap_bits() method
