### ISSUE TITLE
1.7.1 don't compile.

### ISSUE THREAD

**Issue by Oppa-YA** [pschatzmann/ESP32-A2DP#246]
Hello! I can't compile "Release v1.7.1 - I2S output in separate task with ringbuffer & new functionality"
While compiling i was getting error `no matching function for call to 'A2DPVolumeControl::get_volume_factor(uint8_t&)'`
It seems it don't like code in the **_BluetoothA2DPSink32.h_**
I was using code from "bt_music_receiver_32bit_ext" example. In version 1.7.0 it is compiling without problems, I was using Arduino IDE 1.8.19 + ESP32 v 2.0.3 latest board versions.
Here is the screenshot of Arduino IDE output while compiling latest 1.7.1:

![1](https://user-images.githubusercontent.com/11776599/175631913-88b4e346-5609-4ccc-a3aa-3843e17495ca.png)

**Comment by pschatzmann** [comment]
I think this example has not been updated for quite some time...
Just change the line to  volumeFactor = volume_control()->get_volume_factor();
The correction has also been committed

**Comment by Oppa-YA** [comment]
Thank you for fast response!
Can confirm it is fixed now and working!
