### ISSUE TITLE
connect bluetooth headset w microphone to esp32? 

### ISSUE THREAD

**Issue by pcace** [pschatzmann/ESP32-A2DP#268]
Hi there, 

i hope i am right here, but i am wondering if it would be possible with your libraray to: 
- connect a bluetooth headset with microphone
- forward bluetooth  mic to a physical audio out
- get audio from physical audio in to bluetooth headset. 

cheers and thanks!

**Comment by pschatzmann** [comment]
I am sorry but I have no clue what you mean with physical audio and connect. 
Like it's explained in the description of the project you can implement 
- an Bluetooth Source which provides audio to a Bluetooth Speaker or Bluetooth Headset (e.g. from a microphone)
- an Bluetooth Sink which plays the audio which is provided by a Bluetooth Source (e.g. a mobile phone)

**Comment by pschatzmann** [comment]
Please note that A2DP is only for playing audio. It does not support headsets with microphones!

**Comment by pcace** [comment]
Quite some time later.. did you by accident came across a way to have handsfree (microphone + audio) available on the esp? 
Cheers and thanks ;)
