### ISSUE TITLE
When I use Bluetooth, I hear a huge current noise

### ISSUE THREAD

**Issue by baloyou** [pschatzmann/ESP32-A2DP#270]
hello , i have a beginner question. 

I connected the GND of the headphones to the GND of the ESP32.

I connected the 22 pins of the ESP32 to the left or right channel of the headphones, and then I heard a huge current noise, and also heard a faint music sound.

Oddly enough, yesterday I could hear normal sound (I forgot the connection method at the time)

**When I connect the 19 pins to the microphone, I can record normally.**

**this is my headphones**

<img width="451" alt="image" src="https://user-images.githubusercontent.com/5190664/180608273-5ffdc75f-8f34-4995-a2d8-5c1d15ff07b9.png">

**this is my code.**

```
#include "BluetoothA2DPSink.h"

BluetoothA2DPSink a2dp_sink;

void setup() {
  

  
  i2s_pin_config_t my_pin_config = {
    .bck_io_num = 26,
    .ws_io_num = 25,
    .data_out_num = 22,
    .data_in_num = I2S_PIN_NO_CHANGE
  };
  a2dp_sink.set_pin_config(my_pin_config);
  a2dp_sink.start("MyMusic");
}
void loop() {
  delay(1000);
}
```

thank you so much!!

**Comment by pschatzmann** [comment]
See https://github.com/pschatzmann/ESP32-A2DP/issues/61
