### ISSUE TITLE
a2dp low volume

### ISSUE THREAD

**Issue by oldmanskier** [pschatzmann/ESP32-A2DP#289]
compiled player-sd-a2dp and get low volume on receiver.  Used different volume levels but the highest is still too low.
Seems as if the power level from the sender is too low.  The same receiver works fine using cell phone.
Arduino IDE
esp32 dev module  esp32-vroom-32

**Comment by pschatzmann** [comment]
You should have a setVolume() call in the player. 
Why don't you just increase the volume ?

**Comment by oldmanskier** [comment]
I have.  All the way to 1.0

**Comment by oldmanskier** [comment]
Not sure why but I removed the multiplier in AudioA2DP.h line 145 for volume.  Entering a 2 digit int for volume in the sketch for player  has increased the receive volume.  Now just have to solve the warbling of the sound.

**Comment by pschatzmann** [comment]
I did not know that A2DPStream also has some volume control: So setting

out.setVolume(1.0); 
player.setVolume(1.0);

should be the correct solution.
