### ISSUE TITLE
Send battery status and headset icon

### ISSUE THREAD

**Issue by Zetta420** [pschatzmann/ESP32-A2DP#293]
Hello, is there any way to send the battery status to the bluetooth icon ? and change the bluetooth icon for headset icon, like industrial bluetooth speakers. Thank you!

**Comment by pschatzmann** [comment]
Currently not via my functionality. But you can still use the underlaying API. I think there is some functionality for the battery status: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/bluetooth/esp_avrc.html
