### ISSUE TITLE
How to disable the call function of phone？

### ISSUE THREAD

**Issue by Toy-Jie** [pschatzmann/ESP32-A2DP#300]
I want to know how to use the microphone and speaker of the mobile phone only for media audio when the phone calls?

**Comment by pschatzmann** [comment]
Your completely wrong here and this has nothing to do with A2DP. I suggest that you maybe search for Hands-Free Profile (HFP)

**Comment by Toy-Jie** [comment]
Thank you very much for your reply，
I have not set HFP，
After the call is connected, the audio signal is still output from ESP32，
I want voice output from ios when I make a call

**Comment by Toy-Jie** [comment]
@pschatzmann
