### ISSUE TITLE
want it to act like a remote control rather than a playback device

### ISSUE THREAD

**Issue by yskim96** [pschatzmann/ESP32-A2DP#306]
there is a separate Bluetooth/Airplay speaker for output.
equipment is multi-pairing state with a mobile device. and working like a speaker remote control (play/stop)

tested result, `a2dp_sink.pause();` is works great, but it's cumbersome as the mobile device's audio source switches every time you control it, and you won't be able to resume playback without touching the mobile device.

taking this into account, is there any way to issue a command without switching the audio source of the mobile device?

thank you

**Comment by pschatzmann** [comment]
You have me completely confused: a2dp_sink implements a bluetooth speaker that can be controlled via AVRC commands.
What do you mean with there is a separate Bluetooth/Airplay speaker ?
What do you mean with switching the audio source. 
I have the impression that you try to do something which is not supported...
