### ISSUE TITLE
I can't flash it into the board

### ISSUE THREAD

**Issue by ENOTSERVICE** [pschatzmann/ESP32-A2DP#311]
I cannot flash to the board - exit status 1
Compilation error for ESP32 Wroom DevKit board.

**Comment by ENOTSERVICE** [comment]
All other firmwares are compiled normally

**Comment by pschatzmann** [comment]
I suggest that you read the error message that you are getting! 
I have no chance to help you if you do not provide me with any information what sketch you try to flash and about your environment. 
The library has been tested with the old Arduino and the new Arduino IDE with ESP32 Versions 1.0.6 up to 2.0.5.

**Comment by pschatzmann** [comment]
closed due to inactivity
