### ISSUE TITLE
enhancement, DSP capabilities

### ISSUE THREAD

**Issue by B4stl3r** [pschatzmann/ESP32-A2DP#314]
Hi Phil,

1st of all, thx for providing this great library !!!

As you already implemented some Volume enhancements (currently still trying to get it running), I would like to ask, what you think about providing DSP capabilities?

As the cheap amplifiers do not have such possibilities, do you think the esp has enough power left to do some processing?
Had also just a quick look, what I can find in regards of DSP:
https://youtu.be/_nCOluMHfGI?t=257
https://github.com/YetAnotherElectronicsChannel/ESP32_Bluetooth_DSP_Speaker/tree/master/code/main

Will give it a try in the next days, but maybe you can let me know your thinking on that.

**Comment by pschatzmann** [comment]
What exactly do you think is missing ?

**Comment by B4stl3r** [comment]
filtering / enhancing of audio? like an equializer?

Or is that already possible? did I miss out something? :O

**Comment by pschatzmann** [comment]
Yes, it is all there. I suggest that you consult the Wiki https://github.com/pschatzmann/arduino-audio-tools/wiki
and class documentation

**Comment by B4stl3r** [comment]
allright, thank you. didn't have a look on your other repo's..
