### ISSUE TITLE
Audio distortion at bad bluetooth connection

### ISSUE THREAD

**Issue by foltos** [pschatzmann/ESP32-A2DP#32]
Hello!

Thank you for this awesome library! 

The problem: 
If my phone sends music to the esp32 and I go away from the esp32(but it not disconnect) or I cover my phone antenna with my hands the sound will be distorted. Is it related to the code? Is it possible that the phone doesn't send signal? Can I detect if the bluetooth doesn't get data and stop the i2s interface?

Best regards

**Comment by pschatzmann** [comment]
Hmm, I honestly don’t know. 

You could try set the „Core Debug Level“ setting to Verbose and check in your log if you get any events that you can handle differently…
