### ISSUE TITLE
Problem with ESP32 2.0.5 board

### ISSUE THREAD

**Issue by RobertoPoprad** [pschatzmann/ESP32-A2DP#325]
The program worked until I installed a new version of the ESP32 V 2.0.5 board. It cannot translate the program and reports errors.

 warning: missing initializer for member 'i2s_driver_config_t::fixed_mclk' [-Wmissing-field-initializers]
 warning: missing initializer for member 'i2s_driver_config_t::mclk_multiple' [-Wmissing-field-initializers]
 warning: missing initializer for member 'i2s_driver_config_t::bits_per_chan' [-Wmissing-field-initializers]
 warning: missing initializer for member 'i2s_pin_config_t::mck_io_num' [-Wmissing-field-initializers]
 error: unused variable 'bda_str' [-Werror=unused-variable]
     const char *bda_str = to_str(last_connection);
                 ^~~~~~~
error: unused variable 'p' [-Werror=unused-variable]
                 uint8_t *p = peer_bd_addr;
error: unused variable 'bda' [-Werror=unused-variable]
             uint8_t *bda = rc->conn_stat.remote_bda;
                      ^~~
cc1plus.exe: some warnings being treated as errors

**Comment by pschatzmann** [comment]
Don't treat warnings as errors! and change the Compiler warnings back to default in the Preferences...
