### ISSUE TITLE
How to send passthrough command and get callback infomation

### ISSUE THREAD

**Issue by biglee991228** [pschatzmann/ESP32-A2DP#33]
thank you pschatzmann so much for your library which is so simple and nice !
now I can connect my android phone to ESP32+PCM5102 and enjoy the music , the great thing is that AVRCP info can show in the serial monitor such as title,artist,palying time ,etc. and my phone controled ESP32 very well.
my question is:
1. how can I get the callback infomation such as the current playing time that lead me to calculate the progress of  the music.this means the callback infomations may invole the stauts such as palying,pause,stop,new track,etc.
2. how can I get the callback infomations of my phone's bluetooth address or name?
3. I want to control the ESP32 from the serial monitor or  arduino button,such as paly,stop,next,prev ,etc
I know that might use the passthrough function. I love arduino very much but my poor C++ skill doesn't support me to write out very comlex sketch.
can everybody help me?THX a lot!

**Comment by pschatzmann** [comment]
Hallo, I am sorry: to most of the questions I don't have a answer. I just have the following hints:
In the Tools -> Core Debug you can set the Debug level Verbose. This will show you the methods which are called and maybe it gives a you a hint from where to get the information.

For 3. you might want to look at the following resolved issue: https://github.com/pschatzmann/ESP32-A2DP/issues/21
