### ISSUE TITLE
Source code too big ESP32 Core V2.05

### ISSUE THREAD

**Issue by AndreasMainz** [pschatzmann/ESP32-A2DP#341]
Hello,

i compiled the esp32-radio, using Arduino IDE with ESP32 Core V2.05, ESP32 Dev Module selected -> the source code is too big:
Der Sketch verwendet 1777053 Bytes (135%) des Programmspeicherplatzes. Das Maximum sind 1310720 Bytes.

means 35% too big. Any tip for size reduction or optimazation?
Many thanks for any support

BR Andreas

**Comment by pschatzmann** [comment]
Just use the partition scheme: Huge App

**Comment by AndreasMainz** [comment]
That's it. Thanks
