### ISSUE TITLE
END function

### ISSUE THREAD

**Issue by mircose** [pschatzmann/ESP32-A2DP#342]
Your library work fine.
I would like to use a2dp_sink.end(true) for close I2S service and release memory for use another library that use I2S bus. But "re-start not supported after end(true)" and if would like restart BT sevice don't work. The function a2dp_sink.end() don't release I2S bus. 
There is a solution?

**Comment by pschatzmann** [comment]
This is a feature of the ESP32 A2DP API and there is nothing I can do about it!
The only way to deal with this is to restart eg. with ESP.restart();
