### ISSUE TITLE
Context in callbacks.

### ISSUE THREAD

**Issue by ArthurKoba** [pschatzmann/ESP32-A2DP#361]
Good day! I have some problems when using your wonderful library.

Initially, when I wrote the code, I did not use OOP, but now I rewrite everything to objects.
Now I have reached the point where I want to pass the a2dp_sink object pointer to my object method, in which I will set all the callbacks.

Since callbacks take functions and not object methods, I can't easily pass them there. Yes, I know that it is possible to pass a static method of an object to the callback setter, but then I will not have access to the context of the object, and I need it.

I found it possible to use lambdas, but they can only be used if the objects are global.

This is how it works, but a a link is passed to the global colorMusic object is passed.

    a2dp_sink.set_raw_stream_reader([] (
        const uint8_t *d, uint32_t l) {ColorMusic::addSamples(d, l, &colorMusic);}
    );

If I try to call the callback setting inside my object in this way, the compiler will not allow this.
    
    a2dp->set_raw_stream_reader(
        [this] (const uint8_t *d, uint32_t l) {ColorMusic::addSamples(d, l, &this);}
    );

I wrote to the chat of experienced C ++ developers, but they reviewed the example and the library, and said that nothing could be done in this case. They suggested possible to implement context transfer.
For example, it would look like this.

    void BluetoothA2DPSink::set_raw_stream_reader(void (*callBack)(const uint8_t*, uint32_t, void *context)){
        this->raw_stream_reader = callBack;
        this->raw_stream_reader_context = context;
    }

    void BluetoothA2DPSink::audio_data_callback(const uint8_t *data, uint32_t len) {
        if (raw_stream_reader != nullptr) {
            (*raw_stream_reader)(data, len, raw_stream_reader_context);
        }
        //...
    }

    class Foo {
        void static addSamples(const uint8_t *data, uint32_t len, void *context) {
            Foo &thisObject = *(Foo*)context;
            auto frame = (Frame*)data;
            //...
        }
    };

In this case, if the context is not needed when using the library, it is enough to pass nullptr to set_raw_stream_reader instead of the context, and if necessary, you can pass anything to the callback.

If you approve of adding such changes, I can implement them and open a pull request from my fork.

**Comment by pschatzmann** [comment]
Don't you think that the approach from the audio-tools library makes more sense: It uses the Arduino streams as abstractions.
If you want to go ahead with your idea, I don't think that this should sit in the basic code. So I suggest that you just create a subclass and add you additional logic to it.

**Comment by ArthurKoba** [comment]
I am not familiar with the audio-tools library. I'm writing a color-music project and I haven't needed it yet. I just want my code to be more correct in terms of architecture and the problem that has arisen does not allow me to move on. I thought that not only I might have such a problem in the future and therefore I propose to add a very useful ability to pass contexts.

In my project, I can easily implement a subclass that will expand the functionality, but other users may also have a problem, I'm a little worried. But if you do not consider it necessary to add this, I can close the issue.

**Comment by pschatzmann** [comment]
Usually it is good enough just to use some global variables in the sketch and use them if you have the need to pull things together. If you have some more complicated need the recommendation is to go for a better abstraction to avoid these kind of dependencies that you want to introduce.

**Comment by pschatzmann** [comment]
I agree that this is true if you have too many. So you should try to keep the Arduino Sketch quite concise and small. In this case there is nothing that speaks against it.

**Comment by ArthurKoba** [comment]
You can familiarize yourself with my project, you will see that it is already large and this is just the preparation of a good basis for the development of a powerful light and music project.

[esp32-color-music](https://github.com/ArthurKoba/esp32-color-music/)

**Comment by pschatzmann** [comment]
Can I convince you to look into the integration with my AudioTools which is based on Arduino Streams?
Then you  could just provide your different stream based output color devices.
This would have the advantage that you could take the audio from anywhere...

**Comment by pschatzmann** [comment]
Can you add some pictures of the LEDs. 
It's hard to figure out how this looks like...

**Comment by ArthurKoba** [comment]
https://www.youtube.com/watch?v=a7UPMGN-h9Q

But this is only the simplest output, on which I check the developed kernel. I have not yet analyzed the frequencies to make the display more beautiful. As soon as I complete a convenient interface for displaying graphs and complete the core, then I will develop color-music modes.

**Comment by pschatzmann** [comment]
I added an [DRAFT example](https://github.com/pschatzmann/arduino-audio-tools/blob/main/examples/tests/fft/fft-ledmatrix/fft-ledmatrix.ino) how an Arduino sketch which updates a LED Matrix could look like using my AudioTools project.
