### ISSUE TITLE
Using as "sender"

### ISSUE THREAD

**Issue by laverdanny** [pschatzmann/ESP32-A2DP#376]
hi
you suggested a way to create a full audio receiver using  internal DAC

Is there a way to encode stereo analog audio and send I2S over BT using the ESP32 ressources only ?

Maybe out of scope, feel free to close then.

Regards

**Comment by pschatzmann** [comment]
Your wording is very confusing and I don't understand what you mean with sending I2S. I2S is a is an electrical serial bus interface! Do you mean PCM data ?

**Comment by pschatzmann** [comment]
I am closing this because you should rather open a discussion and I can't see any issue here.
