### ISSUE TITLE
Is there plan to support AAC or other codecs?

### ISSUE THREAD

**Issue by ygnid** [pschatzmann/ESP32-A2DP#384]
Thanks very much for your excellent work of this project! I'm wondering if there is plan to support MP3/AAC or other codecs, such as aptX?

**Comment by pschatzmann** [comment]
https://github.com/pschatzmann/ESP32-A2DP/discussions/216

**Comment by pschatzmann** [comment]
IDF 6.1 is supporting different codecs (see https://github.com/pschatzmann/ESP32-A2DP/discussions/805)
