### ISSUE TITLE
Cannot compile on DFRobot Firebeetle ESP32-E

### ISSUE THREAD

**Issue by gitmaxhub** [pschatzmann/ESP32-A2DP#386]
I've just setup the Arduino IDE to work with this ESP32, I've installed this library and when I try to upload the simple example (or any), it instantly fails to compile with the log below.
Is this a bug or is it not compatible with this board? What can I do? I'd really love to use this library.

/Users/user/Documents/Arduino/libraries/ESP32-A2DP/src/BluetoothA2DPSink.cpp: In constructor 'BluetoothA2DPSink::BluetoothA2DPSink()':
/Users/user/Documents/Arduino/libraries/ESP32-A2DP/src/BluetoothA2DPSink.cpp:44:30: error: 'I2S_MCLK_MULTIPLE_DEFAULT' was not declared in this scope
             .mclk_multiple = I2S_MCLK_MULTIPLE_DEFAULT,
                              ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/user/Documents/Arduino/libraries/ESP32-A2DP/src/BluetoothA2DPSink.cpp:44:30: note: suggested alternative: 'RTC_CLK_CONFIG_DEFAULT'
             .mclk_multiple = I2S_MCLK_MULTIPLE_DEFAULT,
                              ^~~~~~~~~~~~~~~~~~~~~~~~~
                              RTC_CLK_CONFIG_DEFAULT
/Users/user/Documents/Arduino/libraries/ESP32-A2DP/src/BluetoothA2DPSink.cpp:45:30: error: 'I2S_BITS_PER_CHAN_DEFAULT' was not declared in this scope
             .bits_per_chan = I2S_BITS_PER_CHAN_DEFAULT
                              ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/user/Documents/Arduino/libraries/ESP32-A2DP/src/BluetoothA2DPSink.cpp:45:30: note: suggested alternative: 'I2S_BITS_PER_SAMPLE_8BIT'
             .bits_per_chan = I2S_BITS_PER_CHAN_DEFAULT
                              ^~~~~~~~~~~~~~~~~~~~~~~~~
                              I2S_BITS_PER_SAMPLE_8BIT
/Users/user/Documents/Arduino/libraries/ESP32-A2DP/src/BluetoothA2DPSink.cpp:49:9: error: no match for 'operator=' (operand types are 'i2s_config_t' and '<brace-enclosed initializer list>')
         };
         ^
In file included from /Users/user/Library/Arduino15/packages/DFRobot/hardware/esp32/0.2.1/tools/sdk/esp32/include/hal/esp32/include/hal/i2s_ll.h:30,
                 from /Users/user/Library/Arduino15/packages/DFRobot/hardware/esp32/0.2.1/tools/sdk/esp32/include/hal/include/hal/i2s_hal.h:28,
                 from /Users/user/Library/Arduino15/packages/DFRobot/hardware/esp32/0.2.1/tools/sdk/esp32/include/driver/include/driver/i2s.h:24,
                 from /Users/user/Documents/Arduino/libraries/ESP32-A2DP/src/BluetoothA2DPCommon.h:36,
                 from /Users/user/Documents/Arduino/libraries/ESP32-A2DP/src/BluetoothA2DPSink.h:18,
                 from /Users/user/Documents/Arduino/libraries/ESP32-A2DP/src/BluetoothA2DPSink.cpp:16:
/Users/user/Library/Arduino15/packages/DFRobot/hardware/esp32/0.2.1/tools/sdk/esp32/include/hal/include/hal/i2s_types.h:134:3: note: candidate: 'i2s_config_t& i2s_config_t::operator=(const i2s_config_t&)'
 } i2s_config_t;
   ^~~~~~~~~~~~
/Users/user/Library/Arduino15/packages/DFRobot/hardware/esp32/0.2.1/tools/sdk/esp32/include/hal/include/hal/i2s_types.h:134:3: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'const i2s_config_t&'
/Users/user/Library/Arduino15/packages/DFRobot/hardware/esp32/0.2.1/tools/sdk/esp32/include/hal/include/hal/i2s_types.h:134:3: note: candidate: 'i2s_config_t& i2s_config_t::operator=(i2s_config_t&&)'
/Users/user/Library/Arduino15/packages/DFRobot/hardware/esp32/0.2.1/tools/sdk/esp32/include/hal/include/hal/i2s_types.h:134:3: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'i2s_config_t&&'
/Users/user/Documents/Arduino/libraries/ESP32-A2DP/src/BluetoothA2DPSink.cpp:60:9: error: no match for 'operator=' (operand types are 'i2s_pin_config_t' and '<brace-enclosed initializer list>')
         };
         ^
In file included from /Users/user/Library/Arduino15/packages/DFRobot/hardware/esp32/0.2.1/tools/sdk/esp32/include/hal/esp32/include/hal/i2s_ll.h:30,
                 from /Users/user/Library/Arduino15/packages/DFRobot/hardware/esp32/0.2.1/tools/sdk/esp32/include/hal/include/hal/i2s_hal.h:28,
                 from /Users/user/Library/Arduino15/packages/DFRobot/hardware/esp32/0.2.1/tools/sdk/esp32/include/driver/include/driver/i2s.h:24,
                 from /Users/user/Documents/Arduino/libraries/ESP32-A2DP/src/BluetoothA2DPCommon.h:36,
                 from /Users/user/Documents/Arduino/libraries/ESP32-A2DP/src/BluetoothA2DPSink.h:18,
                 from /Users/user/Documents/Arduino/libraries/ESP32-A2DP/src/BluetoothA2DPSink.cpp:16:
/Users/user/Library/Arduino15/packages/DFRobot/hardware/esp32/0.2.1/tools/sdk/esp32/include/hal/include/hal/i2s_types.h:180:3: note: candidate: 'i2s_pin_config_t& i2s_pin_config_t::operator=(const i2s_pin_config_t&)'
 } i2s_pin_config_t;
   ^~~~~~~~~~~~~~~~
/Users/user/Library/Arduino15/packages/DFRobot/hardware/esp32/0.2.1/tools/sdk/esp32/include/hal/include/hal/i2s_types.h:180:3: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'const i2s_pin_config_t&'
/Users/user/Library/Arduino15/packages/DFRobot/hardware/esp32/0.2.1/tools/sdk/esp32/include/hal/include/hal/i2s_types.h:180:3: note: candidate: 'i2s_pin_config_t& i2s_pin_config_t::operator=(i2s_pin_config_t&&)'
/Users/user/Library/Arduino15/packages/DFRobot/hardware/esp32/0.2.1/tools/sdk/esp32/include/hal/include/hal/i2s_types.h:180:3: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'i2s_pin_config_t&&'

exit status 1

Compilation error: exit status 1

**Comment by pschatzmann** [comment]
This libaray works if you use the Arduino Stack from Espressif: here are the installation instructions: https://espressif-docs.readthedocs-hosted.com/projects/arduino-esp32/en/latest/installing.html

As you can see the error comes form /Users/user/Library/Arduino15/packages/DFRobot/hardware/esp32 and not from my library!
