### ISSUE TITLE
Only one channel is working

### ISSUE THREAD

**Issue by Bl4ckHol3ee** [pschatzmann/ESP32-A2DP#389]
Hey there, 

I got a little problem with my audio-output.

The problem is, that only one channel is working, the other one is not playing anything at all. 

I already tried to play musik from a normal aux to chinch and there it is working properly.

Could you tell me how i fix the problem, please. Thank you anyway!!

**Comment by pschatzmann** [comment]
I have no idea what scenario you talk about.
- What sketch are you using ?
- What is your hardware ?
Assuming that you try a A2DP Sink with I2S most likely you did not connect the pins properly!
