### ISSUE TITLE
Read current song title

### ISSUE THREAD

**Issue by Sausebraus** [pschatzmann/ESP32-A2DP#434]
Hello,

is it somehow possible to read the current song title and artist from the users phone? I am considering using a small OLED screen to display this information. 

Another question: is it possible for the esp32 to get informed when the user pauses the audio on the phone? Currently my esp thinks the music is still playing even tho it is paused by the user on the phone.

Thank you in advance for your help

**Comment by pschatzmann** [comment]
Your first question is described in the Readme under Support for Metadata.
For your second question did you try the get_audio_state or better the related callback method ?
,
