### ISSUE TITLE
Get device name on pairing request impossible

### ISSUE THREAD

**Issue by mmar22** [pschatzmann/ESP32-A2DP#453]
For showing requesting info on display with code i require device name.
Actual implement show unknown. I try modify and ask device name gap , but reply from iphone in pairing state isnt handled or sended.
Who know. But on moment when pair request window on iphone end timeout, name is received.
`a2dp_sink.get_connected_source_name()`

Ofcourse with my modified code. Calling in case ESP_BT_GAP_CFM_REQ_EVT: 
`esp_bt_gap_read_remote_name(peer_bd_addr)`

**Comment by pschatzmann** [comment]
I cat't see any bug in my code here
