### ISSUE TITLE
Adding record feature in A2DP sink

### ISSUE THREAD

**Issue by rmond18** [pschatzmann/ESP32-A2DP#46]
Is it possible to add a feature where a microSD card is connected and can record a the received data by the A2DP sink with a push button control?

I have found [this](https://github.com/atomic14/esp32_sdcard_audio) which do the the feature that I said but I'm not sure how to integrate it with the A2DP sink code, but I'm currently trying. Do you have any tips? 

Thank you very much!

**Comment by pschatzmann** [comment]
I propose that you have a look at my new library

https://github.com/pschatzmann/arduino-audio-tools

With this it should be very easy to combine any sound input source with any sound output…
