### ISSUE TITLE
Cover Art from Bluetooth?

### ISSUE THREAD

**Issue by TildeWill** [pschatzmann/ESP32-A2DP#468]
Is there a way to get the images for the cover art from the sink? I see in the [espressif docs](https://docs.espressif.com/projects/esp-idf/en/v4.2.1/esp32/api-reference/bluetooth/esp_avrc.html#_CPPv443ESP_AVRC_FEAT_FLAG_COVER_ART_GET_IMAGE_PROP) there's flags like `ESP_AVRC_FEAT_FLAG_COVER_ART_GET_IMAGE` and another one `ESP_AVRC_FEAT_FLAG_COVER_ART_GET_LINKED_THUMBNAIL`. If I could pluck these out to get the images in the same way you can grab the title and artist it'd take my project to the next level.

**Comment by pschatzmann** [comment]
https://github.com/pschatzmann/ESP32-A2DP#support

I don't understand why you report this as a bug. 
This is clearly not supported by my library!

If you double check the IDF documentation you will also not find any method that would support the esp_avrc_feature_flag_t enum.
