### ISSUE TITLE
ESP_BT_GAP_ACL_CONN_CMPL_STAT_EVT was not declared in this scope

### ISSUE THREAD

**Issue by thezenox** [pschatzmann/ESP32-A2DP#476]
With current master of arduino-esp32 (02e31b4) I get
`'ESP_BT_GAP_ACL_CONN_CMPL_STAT_EVT' was not declared in this scope`
with branch IDF release/v4.4 everything works fine. See esp_gap_bt_api.h.

Just as a hint if someone gets this error.

**Comment by pschatzmann** [comment]
Please check the other close issues and discussions.
It's your mistake for using an old ESP32 version!
