### ISSUE TITLE
Trouble with connect_to ...

### ISSUE THREAD

**Issue by mmar22** [pschatzmann/ESP32-A2DP#480]
### Problem Description

I start with 1.7.3 my device connects to last and play ok . Then i call
`void a2discon()
{
  if(a2dp_sink.is_connected()) a2dp_sink.disconnect(); 
  while(a2dp_sink.is_connected()) delay(10);
}

void a2con(uint8_t indexPD)
{
  a2dp_sink.connect_to(storedPD[indexPD].addr);
}`

device is disconnected, but next paired in my db not connect, or if i try some delays sometimes connect sometimes not.
How is right steps and timing to disconect device 1 and connect device 2 ? From ESP side.
### Device Description

ESP32

### Sketch

```cpp
spdif no I2S variant sink
```

### Other Steps to Reproduce

same situation 1.7.4 A2DP

too buggy showed last instead new 
`bool BluetoothA2DPCommon::connect_to(esp_bd_addr_t peer){
    ESP_LOGW(BT_AV_TAG, "connect_to to %s", to_str(last_connection));`

and FYI build without I2S require patch BluetoothA2DPSink.cpp against error not exist i2s task
`void ccall_i2s_task_handler(void *arg) {
  ESP_LOGD(BT_AV_TAG, "%s", __func__);
  if (actual_bluetooth_a2dp_sink)
    actual_bluetooth_a2dp_sink->i2s_task_handler(arg);
}
`
need add
`#if A2DP_I2S_SUPPORT
void ccall_i2s_task_handler(void *arg) {
  ESP_LOGD(BT_AV_TAG, "%s", __func__);
  if (actual_bluetooth_a2dp_sink)
    actual_bluetooth_a2dp_sink->i2s_task_handler(arg);
}
#endif`

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
There is a good reason why I am asking to provide the Arduino ESP32 core version number! So please provide the missing information.

I suggest that you activate the logging and analyse the events: In the end it is up to the device that you want to connect to if a new connection is accepted or not.

**Comment by mmar22** [comment]
PACKAGES:
 - framework-arduinoespressif32 @ 3.20009.0 (2.0.9)
 - tool-esptoolpy @ 1.40501.0 (4.5.1)
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5

**Comment by pschatzmann** [comment]
https://github.com/pschatzmann/ESP32-A2DP/commit/2f7b42e00d8cbf8e5937f5bf6dc2de321842644a

ps.
2.0.9 is pretty old now, the latest release is 2.0.13 now

**Comment by mmar22** [comment]
Very inteligent reply. Is irelevant here if 2.0.9 or 1234 , your class connect_to require some control of state previous disconnect command. Or if you dont know timing write it .

**Comment by pschatzmann** [comment]
I think it would be saver to rely on the connection_state() method for your check and wait for the correct status.
You are currently only checking if != APP_AV_STATE_CONNECTED
