### ISSUE TITLE
Pin code feature.

### ISSUE THREAD

**Issue by ScaredyCat** [pschatzmann/ESP32-A2DP#49]
Is there any kind of BT paring pin code facility built in to this library?

If I connect my phone, for example then turn off bt on it the esp32 will start advertising its availability... and *anyone* can connect.

**Comment by tv4you2016** [comment]
https://github.com/tv4you2016/ESP32-A2DP

**Comment by pschatzmann** [comment]
https://github.com/pschatzmann/ESP32-A2DP/wiki/Access-Protection---Authentication
