### ISSUE TITLE
Latest version not linking 

### ISSUE THREAD

**Issue by tooxo** [pschatzmann/ESP32-A2DP#494]
### Problem Description

During linking an error occures.
```
... /ld: .pio/build/lolin32_lite/libf63/libESP32-A2DP.a(BluetoothA2DPCommon.cpp.o):(.rodata._ZTV19BluetoothA2DPCommon[vtable for BluetoothA2DPCommon]+0x78): undefined reference to `BluetoothA2DPCommon::set_scan_mode_connectable_default()'

```

### Device Description

Lolin32 

### Sketch

```cpp
platformio.ini

[env:lolin32_lite]
platform = espressif32
board = lolin32_lite
framework = arduino
build_type = debug
lib_deps =
	https://github.com/pschatzmann/ESP32-A2DP#v1.7.4
```

### Provide your Version of the EP32 Arduino Core (or the IDF Version)

2.0.11

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
And now I am supposed to reproduce your issue ?
