### ISSUE TITLE
Documentation for A2DP Sink Library?

### ISSUE THREAD

**Issue by facerollonkeyboard** [pschatzmann/ESP32-A2DP#5]
Could you please provide documentation for the library you created for esp32 A2DP sink application with the Arduino IDE?

**Comment by pschatzmann** [comment]
I was hoping that the readme in https://github.com/pschatzmann/ESP32-A2DP provides enough to jump start the development.  

In addition you can also find info in my blogs e.g. https://www.pschatzmann.ch/home/2020/09/15/sending-sound-from-an-esp32-to-a-bluetooth-sink-e-g-bluetooth-speaker/
