### ISSUE TITLE
Typo in serial speed in "bt_music_receiver_rssi"?

### ISSUE THREAD

**Issue by TombusPL** [pschatzmann/ESP32-A2DP#514]
### Problem Description

Typo of value of speed serial:

file: bt_music_receiver_rssi.ino

```
is: 30: Serial.begin(119200);
should be: 30: Serial.begin(19200);
```

### Device Description

Library

### Sketch

```cpp
Just typo in number
```

### Provide your Version of the EP32 Arduino Core (or the IDF Version)

main

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
No it should be 115200.
The correction has been committed
