### ISSUE TITLE
How to integrate this using PAJ7620 as a gesture controller?

### ISSUE THREAD

**Issue by galahan1987** [pschatzmann/ESP32-A2DP#532]
### Problem Description

I want to integrate this using PAJ7620 as a gesture controller but I don't know how, I hope you can help me. Thanks in advance

### Device Description

ESP32 Devkit

### Sketch

```cpp
related part of the code
```

### Provide your Version of the EP32 Arduino Core (or the IDF Version)

devkit v1

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
I don't see how this [would be a bug ](https://github.com/pschatzmann/ESP32-A2DP?tab=readme-ov-file#support)in the A2DP library.
