### ISSUE TITLE
PCM5102A Lots of different types of noise (clicking, high frequency, low frequency)

### ISSUE THREAD

**Issue by Tuxorials** [pschatzmann/ESP32-A2DP#556]
### Problem Description

As soon as the esp+PCM5102A breakout (the aliexpress cheapo variant) are connected to the amp, a plethora of noise is made depending on if the device is connected or not. Check the attached video (Everything is recorded at 20cm distance on an AT2020 Microphone)

https://github.com/pschatzmann/ESP32-A2DP/assets/61655859/62e22b42-851a-4adb-8c74-cad123084615

### Device Description

ESP32 Wroom (just the normal version you see everywhere (im yet to find the actual name for the board))
PCM5102A ([this one](https://www.aliexpress.com/item/1005006104038963.html)) 

### Sketch

```cpp
#include "AudioTools.h"
#include "BluetoothA2DPSink.h"

I2SStream i2s;
BluetoothA2DPSink a2dp_sink(i2s);

void setup() {
  Serial.begin(115200);
  pinMode(27,INPUT);
  pinMode(21,OUTPUT);
  auto cfg = i2s.defaultConfig();
  cfg.pin_bck = 4;
  cfg.pin_ws = 15;
  cfg.pin_data = 2;
  i2s.begin(cfg);

  static const i2s_config_t i2s_config = {
        .mode = (i2s_mode_t) (I2S_MODE_MASTER | I2S_MODE_TX),
        .sample_rate = 44100,
        .bits_per_sample = I2S_BITS_PER_SAMPLE_16BIT,
        .channel_format = I2S_CHANNEL_FMT_RIGHT_LEFT,
        .communication_format = (i2s_comm_format_t) (I2S_COMM_FORMAT_I2S_MSB | I2S_COMM_FORMAT_I2S_LSB),
        .intr_alloc_flags = 0, // default interrupt priority
        .dma_buf_count = 48,
        .dma_buf_len = 256,
        .use_apll = false,
        .tx_desc_auto_clear = true // avoiding noise in case of data unavailability
  };
  a2dp_sink.set_i2s_config(i2s_config);

  a2dp_sink.set_channels (I2S_CHANNEL_STEREO);
  a2dp_sink.set_auto_reconnect(true, 1000);

  a2dp_sink.start("Big Speakers");
}

void loop() {
 delay(50); //Simplified, normally theres battery voltage measurement going on here
}
```

### Other Steps to Reproduce

I tried both a Pixel 8 and a Galaxy A23 5G as bluetooth devices. the amps arent high quality by any means (3,80€ on aliexpress) but they dont cause any noise when the input is bridged as can be seen in the video

### Provide your Version of the EP32 Arduino Core (or the IDF Version)

2.0.13

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
Your code does not make any sense at all!
Please stick to the documented functionality that you can find in the Readme!

If you absolutly want to use the legacy functionality, you can find the doucmentation in the Wiki

**Comment by pschatzmann** [comment]
No, it is not mixed: The Readme contains the actual API
The Legacy API is documented in a separate Wiki
Finally, there is a Wiki for the different DACs

**Comment by pschatzmann** [comment]
Did you check the solder bridges ?

**Comment by pschatzmann** [comment]
I suggest to do the tests with [a simpler sketch](https://github.com/pschatzmann/arduino-audio-tools/tree/main/examples/examples-stream/streams-generator-i2s) and test your I2S functionality first

**Comment by pschatzmann** [comment]
If the sine wave sketch does not give a clean sound, set the log level to Warning.

I would not recognize your recorded sound. Do you get the same when you test with earphones ?

**Comment by pschatzmann** [comment]
Do you get at least a clean sine signal ?
What is your power supply ?

**Comment by pschatzmann** [comment]
Is this with log level Warning ?
