### ISSUE TITLE
PLAY_STATUS_CHANGE event added but no show

### ISSUE THREAD

**Issue by algavrik** [pschatzmann/ESP32-A2DP#56]
Hi there,
Thanks for your code and your work. I'd like to add more functionality, particulary PLAY_STATUS_CHANGE event.
1. In BluetoothA2DPSink.cpp I added in av_notify_evt_handler()
    case ESP_AVRC_RN_PLAY_STATUS_CHANGE:
        ESP_LOGD(BT_AV_TAG, "%s ESP_AVRC_RN_PLAY_STATUS_CHANGE %d", __func__, event_id);
        av_track_status_change();
        break;
2. in av_hdl_avrc_evt() added
case ESP_AVRC_CT_PLAY_STATUS_RSP_EV:
 
code compiles ok but no show PLAY_STATUS_CHANGE event in debug.

**Comment by pschatzmann** [comment]
It is my understandcing that this functionality is not available in the ESP32 Release supported by Arduino.
Unfortunately we need to wait until Arduino supports a newer version.

**Comment by alexus2033** [comment]
You can use [ESP_A2D_AUDIO_STATE_EVT](https://docs.espressif.com/projects/esp-idf/en/v3.0-rc1/api-reference/bluetooth/esp_a2dp.html#_CPPv221esp_a2d_audio_state_t) that works with Arduino IDE
Example:
https://github.com/alexus2033/ESP32-A2DP/blob/master/src/BluetoothA2DPSink.cpp
