### ISSUE TITLE
Double metadata notifications response on provoked track change

### ISSUE THREAD

**Issue by martinroger** [pschatzmann/ESP32-A2DP#561]
### Problem Description

When running any of the basic examples of the A2DP Sink that queries metada update notifications, I noticed that sometimes - and mostly when - doing a track change either directly on the TG or via the CT (a2dp_sink.next()), I would get double and even triple notifications with the new song metadata in a short timeframe, as if _av_new_track()_ got called twice by two different places (I couldn't find evidence of that, even going to DEBUG level ESP messages).

The expected behaviour would be to get a single response metadata notification when changing tracks either via the CT, or directly on the TG (e.g. pressing the next button on the phone).

The current work-around is to implement some basic data-debouncing and compares, since these 2-3 responses are usually fired very rapidly together.

I noticed that sometimes between those duplicate metadata responses, the track duration attribute isn't updated on the first 1-2 responses but is updated on the third. This makes me think that this may be also possibly related to the type of TG device responding. Could this be just a quirk of how AVRCP is sometimes implemented in the wild and not an actual issue ?

### Device Description

NodeMCU 32S, which is based on a WROOM-32. I also observed the same behaviour on a Sparkfun Thing Plus which I believe to run the WROOM-32E. It is connected to an external UDA1334A DAC, but it also shows the issue with the i2s pointing to the internal DAC.

### Sketch

```cpp
//bt_music_receiver_with_metadata.ino exhibits this behaviour, apparently related to the metadata callback being called twice :

void avrc_metadata_callback(uint8_t id, const uint8_t *text) {
  Serial.printf("==> AVRC metadata rsp: attribute id 0x%x, %s\n", id, text);
  if (id == ESP_AVRC_MD_ATTR_PLAYING_TIME) {
    uint32_t playtime = String((char*)text).toInt();
    Serial.printf("==> Playing time is %d ms (%d seconds)\n", playtime, (int)round(playtime/1000.0));
  }
}
```

### Other Steps to Reproduce

I tried : 
- Changing the metadata attribute mask to every attribute possible, only some, and only one : no real change
- Using different phones (Pixel 5, iPhone 6) with different music apps running (Spotify x2, Apple Music) : no particular difference
- Tried also running other callbacks together in an "all-in-one" example : play_pos, connection_state, audio_state. No change.
- Did try with IDF 6.6.0 and 6.7.0, no changes in the results

### Provide your Version of the EP32 Arduino Core (or the IDF Version)

IDF 6.7.0, Arduino Core 2.0.16, ESP32-A2DP 1.8.1+sha.b0ad45d

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
I think the application works as designed: I am just passing all the events that are received to the callback and I guess that they have implemented it that way to make sure that no events gets lost.

Usually this is not a problem because the events are used to update the information locally.

If your application logic relies on some unique events, you will need to implement your own logic
