### ISSUE TITLE
bluetooth devices with address starting 00 will not auto reconnect

### ISSUE THREAD

**Issue by nimitch** [pschatzmann/ESP32-A2DP#58]
the function  in BluetoothA2DPSink.cpp

bool BluetoothA2DPSink::has_last_connection() {  
            return last_connection[0] != 0;
 }

will return false if the address begins with 00 so will not attempt to reconnect.
I worked around it by checking each byte and returning on the first non zero,  but you may want to use a different solution

**Comment by pschatzmann** [comment]
I have committed a correction

**Comment by nimitch** [comment]
Thank you for you hard work on developing this library, it is much
appreciated

Kind regards.. nick
