### ISSUE TITLE
basic-adc-a2dp has “snaps" and "crackles"

### ISSUE THREAD

**Issue by StreakingJerry** [pschatzmann/ESP32-A2DP#596]
### Problem Description

I tried to make a low latency aux to bluetooth audio adapter by ESP32. I have made some modification to the example `basic-adc-a2dp` to make it fit with ESP32 version 3.0.0. My code is pasted in the Sketch part:

I use a 3.5mm audio cable from my laptop as the audio source. and with such a circuit but without Cout  to make the signal in between 0-3.3v.
![image](https://github.com/user-attachments/assets/be8ebb5c-8ddf-4667-9127-7241c3986ca7)

The output of opamp connect to the pin 34 and 35 of ESP32.

However, the sound played in my bluetooth speaker is “snaps" and "crackles". I guess the reason might be that occasionally the time between the callback function could be too large to make the sound discontinuous. 

If this is the case, then whether it is possible to use two core of the ESP32 to record and play simultaneously?

### Device Description

ESP32-PICO-D4

### Sketch

```cpp
#include "AudioTools.h"
#include "BluetoothA2DPSource.h"

AnalogAudioStream adc;
BluetoothA2DPSource a2dp_source;
ConverterScaler<int16_t> scaler(1.0, -1820, 32767);


int32_t get_data_frames(Frame *frame, int32_t frame_count) {
  uint8_t *data = (uint8_t *)frame;
  size_t resultBytes = adc.readBytes(data, frame_count * 4);
  scaler.convert(data, resultBytes);


  // Serial.println("start 128 frame:");
  // int16_t *sample = (int16_t *)frame;
  // int size = resultBytes / 4;
  // for (int j = 0; j < size; j++) {
  //   Serial.print(*sample++);
  //   Serial.print(", ");
  //   Serial.println(*sample++);
  // }
  return frame_count;
}

// Arduino Setup
void setup(void) {
  Serial.begin(115200);

  // start i2s input with default configuration
  Serial.println("starting I2S-ADC...");

  auto adcConfig = adc.defaultConfig(RX_MODE);
  adcConfig.sample_rate = 44100;
  adcConfig.adc_bit_width = 12;
  adcConfig.adc_calibration_active = false;
  adcConfig.is_auto_center_read = false;
  adcConfig.adc_attenuation = ADC_ATTEN_DB_12;
  adcConfig.channels = 2;
  adcConfig.adc_channels[0] = ADC_CHANNEL_6;
  adcConfig.adc_channels[1] = ADC_CHANNEL_7;
  adc.begin(adcConfig);

  // start the bluetooth
  Serial.println("starting A2DP...");
  // a2dp_source.set_auto_reconnect(false);
  a2dp_source.start("Minibar B1239", get_data_frames);
  // a2dp_source.set_volume(20);
}

// Arduino loop - repeated processing
void loop() {
  delay(1000);
}
```

### Provide your Version of the EP32 Arduino Core (or the IDF Version)

3.0.3

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
[You need to perform a proper analysis to identify where your issue is](https://github.com/pschatzmann/arduino-audio-tools/wiki/It's-not-working).

Try to record a sine wave and output it as CSV via the Serial Plotter.
