### ISSUE TITLE
BT sink, WDT crash with Arduino 3.0.5

### ISSUE THREAD

**Issue by tueddy** [pschatzmann/ESP32-A2DP#606]
### Problem Description

Hi PSchatzmann, sorry do disturb again ;-(

I'm porting the BT part of [ESPuino MP3 kidsplayer ](https://github.com/biologist79/ESPuino)to Arduino 3. ESP32-A2DP on Arduino 2 works perfectly fine both source/sink!

BT-Source seems to be fine on Arduino 3 but BT-Sink triggers a Watchdog reset. 
I can hear clear sound for just about  2 seconds then ESP32 crashes. 
This is the stacktrace:

`I [5099] Bluetooth sink => connection state: Connected (Free heap: 112084 Bytes)
D [5107] Bluetooth => RSSI value: -16
D [5312] Bluetooth => AVRC Title: Normale Kartoffeln auf die 1
D [5313] Bluetooth => AVRC Artist: Julian Benz & Florian Wirtz
D [5313] Bluetooth => AVRC Album: Normale Kartoffeln auf die 1 - Single
D [5323] Bluetooth => AVRC Track-No: 1
D [5323] Bluetooth => AVRC Number of tracks: 23
D [5334] Bluetooth => AVRC Genre: Schlager
I [10003] Aktuelle Batteriespannung: 3.97 V
I [10004] Aktuelle Batterieladung: 84.53 %
I [20293] Bluetooth sink => audio state: Started (Free heap: 109616 Bytes)
E (34083) task_wdt: Task watchdog got triggered. The following tasks/users did not reset the watchdog in time:
E (34083) task_wdt:  - IDLE0 (CPU 0)
E (34083) task_wdt: Tasks currently running:
E (34083) task_wdt: CPU 0: BTC_TASK
E (34083) task_wdt: CPU 1: IDLE1
E (34083) task_wdt: Aborting.
E (34083) task_wdt: Print CPU 0 (current core) backtrace

Backtrace: 0x4025f41b:0x3ffdc060 0x4025be4d:0x3ffdc080 0x4025ebb5:0x3ffdc0a0 0x40123535:0x3ffdc0c0 0x4025e9a9:0x3ffdc0e0 0x40122387:0x3ffdc100 0x40162ab1:0x3ffdc120 0x4015dedd:0x3ffdc160 0x4015de79:0x3ffdc180 0x4009a5a6:0x3ffdc1b0
  #0  0x4025f41b in Print::write(unsigned char const*, unsigned int) at C:/Users/dcars/.platformio/packages/framework-arduinoespressif32-src-7dd98b7103bed509926a4d02dd75f518/cores/esp32/Print.cpp:40
  #1  0x4025be4d in BluetoothA2DPOutputPrint::write(unsigned char const*, unsigned int) at .pio/libdeps/lolin_d32_pro_sdmmc_pe/ESP32-A2DP/src/BluetoothA2DPOutput.h:132
  #2  0x4025ebb5 in BluetoothA2DPSink::i2s_write_data(unsigned char const*, unsigned int) at .pio/libdeps/lolin_d32_pro_sdmmc_pe/ESP32-A2DP/src/BluetoothA2DPSink.cpp:1245
      (inlined by) BluetoothA2DPSink::i2s_write_data(unsigned char const*, unsigned int) at .pio/libdeps/lolin_d32_pro_sdmmc_pe/ESP32-A2DP/src/BluetoothA2DPSink.cpp:1231
  #3  0x40123535 in BluetoothA2DPSink::write_audio(unsigned char const*, unsigned int) at .pio/libdeps/lolin_d32_pro_sdmmc_pe/ESP32-A2DP/src/BluetoothA2DPSink.h:534
  #4  0x4025e9a9 in BluetoothA2DPSink::audio_data_callback(unsigned char const*, unsigned long) at .pio/libdeps/lolin_d32_pro_sdmmc_pe/ESP32-A2DP/src/BluetoothA2DPSink.cpp:1052   
  #5  0x40122387 in ccall_audio_data_callback at .pio/libdeps/lolin_d32_pro_sdmmc_pe/ESP32-A2DP/src/BluetoothA2DPSink.cpp:1186
  #6  0x40162ab1 in btc_a2d_data_cb_to_app at C:/Users/dcars/.platformio/packages/framework-espidf@src-29cf07cc82e49157db19869ff2d1be3f/components/bt/host/bluedroid/btc/profile/std/a2dp/btc_a2dp_sink.c:150
      (inlined by) btc_a2dp_sink_handle_inc_media at C:/Users/dcars/.platformio/packages/framework-espidf@src-29cf07cc82e49157db19869ff2d1be3f/components/bt/host/bluedroid/btc/profile/std/a2dp/btc_a2dp_sink.c:581
      (inlined by) btc_a2dp_sink_data_ready at C:/Users/dcars/.platformio/packages/framework-espidf@src-29cf07cc82e49157db19869ff2d1be3f/components/bt/host/bluedroid/btc/profile/std/a2dp/btc_a2dp_sink.c:370
      (inlined by) btc_a2dp_sink_data_ready at C:/Users/dcars/.platformio/packages/framework-espidf@src-29cf07cc82e49157db19869ff2d1be3f/components/bt/host/bluedroid/btc/profile/std/a2dp/btc_a2dp_sink.c:347
  #7  0x4015dedd in osi_thread_generic_event_handler at C:/Users/dcars/.platformio/packages/framework-espidf@src-29cf07cc82e49157db19869ff2d1be3f/components/bt/common/osi/thread.c:425
      (inlined by) osi_thread_generic_event_handler at C:/Users/dcars/.platformio/packages/framework-espidf@src-29cf07cc82e49157db19869ff2d1be3f/components/bt/common/osi/thread.c:418
  #8  0x4015de79 in osi_thread_run at C:/Users/dcars/.platformio/packages/framework-espidf@src-29cf07cc82e49157db19869ff2d1be3f/components/bt/common/osi/thread.c:165
  #9  0x4009a5a6 in vPortTaskWrapper at C:\Users\dcars\.platformio\packages\framework-espidf@src-29cf07cc82e49157db19869ff2d1be3f\components\freertos\FreeRTOS-Kernel\portable\xtensa/port.c:162

ELF file SHA256: 612b7970bbaa1015` 

Any hint what goes wrong here? Am i miss something?

### Device Description

Lolin D32 Pro with PSRAM

### Sketch

```cpp
ESPuino project, bluetooth part:

https://github.com/biologist79/ESPuino/blob/dev/src/Bluetooth.cpp
```

### Provide your Version of the EP32 Arduino Core (or the IDF Version)

Arduino 3.0.5, ESP-IDF 5.1.4

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
Please report your issue to the ESPuino project.
