### ISSUE TITLE
ESP32 internal DAC playing music with noise

### ISSUE THREAD

**Issue by wamk9** [pschatzmann/ESP32-A2DP#61]
Hi Everyone!

I'm using a DEVKIT V1 (ESP32 WROOM 32) to test my project, but when i start a BT connection with my Android using the internal DAC of ESP32 i hear a lot of noise when music played (of course, if they is not playing too).

My question is, this "issue" is caused by internal DAC or my "hardware"? 

I'm using exemple codes only, with a P2 jack removed of a motherboard and connected in GPIO25, GPIO26 and GND pins, my board are powered with a 5v~1A power supply on VIN/GND pins and nothing more, I'm not using any amplifier, only my headphone connected on P2...

**Comment by SlowLogicBoy** [comment]
Having, same issue, searching for solutions, I think it's isolation problem, it picks up noise of data that's going through the board.
https://newbedev.com/esp32-adc-not-good-enough-for-audio-music

**Comment by pschatzmann** [comment]
I just did some testing today with a cheap china DEVKIT V1 from DOIT and I confirm that I am getting some noise as well, so I guess this is a generic problem coming from the radiation of the cpu and the bluetooth emitter.

The most reliable way is to use an external DAC: https://github.com/pschatzmann/ESP32-A2DP/wiki/External-DAC

**Comment by 0neday** [comment]
when I connect power suppy using 3.3v of esp32 for AMP,  and stop play music, there is no Common Ground noise，but when I play music, there have noise again. 
I guess, the noise is produced by esp32 bluetooth emmiter. so there no good solution for remove noise when you use internel DAC.
Maybe externel DAC could fix this

**Comment by pschatzmann** [comment]
Yes it will!

**Comment by dcerisano** [comment]
Try a different ground pin on the ESP32 for your sound stage.
Some ground pins definitely give more distortion than others, especially on cheap knockoff ESP32s.

**Comment by clarkbremer** [comment]
> Try a different ground pin (there are several) on the ESP32 for your sound stage.
> Some ground pins definitely give more distortion than others, especially on cheap knockoff ESP32s, especially with BLE initialized.
> 

Wait... There are cheap knockoff esp32s out there?  Do you mean devkit boards, or the esp32 modules themselves?

**Comment by dcerisano** [comment]
> Wait... There are cheap knockoff esp32s out there? Do you mean devkit boards, or the esp32 modules themselves?

I mean the boards. The cheaper ones create RF distortion on their common grounds. This can be minimized by using a piezo speaker wired in H-Bridge configuration on pins 25 and 26 and using a dual-GPIO-pin AC driver rather than the usual single-pin DC drivers.

**Comment by pschatzmann** [comment]
The general recommendation is to use the internal DAC only for testing or if noise is acceptable. Otherwise use a proper I2S DAC!

**Comment by fa1ke5** [comment]
Большинство усилителей имеют дифференциальные входы IN+ и IN-, если подключить их оба к GPIO то шумы питания должны взаимно компенсироваться, но это только теория.

**Comment by mrhempman69** [comment]
You guys got improved audio quality by placing capacitors like this? (In "series" as the image shows...)
![image](https://github.com/pschatzmann/ESP32-A2DP/assets/41412018/058348e3-e0ca-4704-abbf-deb346429937)

**Comment by fa1ke5** [comment]
Это устранит проблему лишь частично, правильное решение подключать источник звука к дифференциальным выходам DAC

**Comment by mrhempman69** [comment]
Sorry, my chinese is a bit rusty... How much for 3 dumplings?

Anyway... It turns out the DAC is fine at higher volumes, because the noise is a problem when it's at lower voltages. I get pretty good results with just a 2-5kiloOhm resistor and the volume at 2/3s or higher.

 The resistors quiet the actual sound that is output through the speakers (so that I can play at high DAC voltage outputs without burning my eardrums, and without it being bothered by the antenna noise).

**Comment by dcerisano** [comment]
Adding inline caps and resistors is effectively creating highpass filters to reduce the RF interference.

**Comment by dcerisano** [comment]
Adding inline caps and resistors is effectively creating highpass filters to reduce the RF interference. This comment "just use a proper I2C DAC" is kind of missing the point. The idea is to minimize BoC by using the internal DAC.

Also the commentator above is writing in cryllic, not hànzì (it's Russian not Chinese) and contained zero dumpling content. See examplar below:

У этого парня фетиш на пельмени
这家伙有饺子癖

**Comment by dcerisano** [comment]
Adding inline caps and resistors is effectively creating highpass filters to reduce the RF interference. This comment "just use a proper I2C DAC" is kind of missing the point. The idea is to minimize BoC by using the internal DAC.

Also the commentator above is writing in cryllic, not hànzì (it's Russian not Chinese) and contained zero dumpling content. See examplar below:

У Хемпмана фетиш на пельмени
亨普曼喜欢饺子

**Comment by bobisaperson1** [comment]
餃子を4個注文してもいいですか？
