### ISSUE TITLE
Bluetooth Serial reconnect turned off when ending a2dp sink

### ISSUE THREAD

**Issue by chamatkari-hub** [pschatzmann/ESP32-A2DP#611]
### Problem Description

I am using **a2dp_sinl.end(true);**  so it is also turning off the reconnect of BT Serial.

### Device Description

ESP32 Dev Kit

### Sketch

```cpp
a2dp_sink.end(true); // it is also turning off the reconnect of Bluetooth serial
```

### Provide your Version of the EP32 Arduino Core (or the IDF Version)

1.0

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
Works as designed: a2dp_sink.end(true) stops all bluetooth and releases all related memory

**Comment by chamatkari-hub** [comment]
But if i want to only stop the reconnect of a2dp sync not the BT Serial then what to do?

**Comment by pschatzmann** [comment]
just call end()

**Comment by chamatkari-hub** [comment]
But i want that if the device reconnects it should not sync the audio...if I just call end() it just disconnects the device if I reconnect to it the audio again start to sync

**Comment by pschatzmann** [comment]
What do you mean with synch the audio ?
Calling end() is stoping the a2dp task and all releated processing

**Comment by chamatkari-hub** [comment]
mainly i am making a speaker with RGB lights with SD Card Playback option so in the starting I broadcast BT Serial for sending Commands through Bluetooth and if the command matched "BT" then the a2dp gets started by a predefined name and if "STOP" is received I want the a2dp to fully stop the broadcast so no one can connect to it till he/she again gives the "BT" command because when I am playing the audio through SD Card then too the a2dp device can be connected and it make a clash

**Comment by pschatzmann** [comment]
You have me completly lost:What Scenario are you talking about ? 
A A2DP Sind or Source ?
Did you activate the auto reconnect ?

**Comment by chamatkari-hub** [comment]
i2s_pin_config_t pin_config = {
        .bck_io_num = I2S_BCK_PIN,
        .ws_io_num = I2S_LRC_PIN,
        .data_out_num = I2S_DATA_PIN,
        .data_in_num = I2S_PIN_NO_CHANGE
      };
      a2dp_sink.set_pin_config(pin_config);      
      a2dp_sink.start("UNITAK MUSIC");

**Comment by chamatkari-hub** [comment]
this is the code which im using for i2s communication with the amplifier and then starting the a2dp_sink

**Comment by chamatkari-hub** [comment]
Bro what do you mean by obolete ESP32...what should I use then?

**Comment by chamatkari-hub** [comment]
Actually im new to esp32 so please guide me a bit

**Comment by pschatzmann** [comment]
The actual ESP32 core version is 3.0.5 with 3.1 coming out soon
You seem to be still uing the old 2.x version

Go to the Boards Manager and make sure that you have the latest release

**Comment by chamatkari-hub** [comment]
![Screenshot 2024-10-08 151022](https://github.com/user-attachments/assets/0a32f135-a47c-4482-b947-56575513190b)
After updating im getting this error

**Comment by pschatzmann** [comment]
Yes, read the REAME of this project !

**Comment by chamatkari-hub** [comment]
I have to use the audio tool library?

**Comment by pschatzmann** [comment]
yes or the i2s output functionality from ESP32 Arduino

**Comment by chamatkari-hub** [comment]
Can i use the audio tools library for syncing the Bluetooth audio as well as can I read audio file from SD Card and send it to the amplifier?

**Comment by pschatzmann** [comment]
Sure, for what file format ?

**Comment by chamatkari-hub** [comment]
WAV

**Comment by pschatzmann** [comment]
Here is an [example](https://github.com/pschatzmann/arduino-audio-tools/tree/main/examples/examples-stream/streams-sd_mp3-i2s): just replace the mp3 decodr with a [wav decoter](https://github.com/pschatzmann/arduino-audio-tools/wiki/Encoding-and-Decoding-of-Audio)

**Comment by chamatkari-hub** [comment]
Let me tell you about my project...I am making a simple speaker in which I want 2 audio sources 
- Bluetooth 
- SD CARD
Hardware : ESP32, RGB LEDs , MAX98357a Amplifier

I want my program to work in a way that if "BT" is received from Bluetooth Serial then the a2dp sync should start for Bluetooth audio okay, but if "SD" is received then the a2dp broadcast should stop and the audio should be played from the SD Card

**Comment by pschatzmann** [comment]
I don't see any problem with this. If you have the issue that the last mobile phone automatically reconnects and plays audio, this might be because you ask this library to do so, and if you didn't then the mobile phone has some automatic reconnect implemented. In this case just disconnect from the mobile phone or change the bluetooth name of the esp32 so that the phone does not find it any more

**Comment by chamatkari-hub** [comment]
Is there any example available for the Bluetooth audio sync?

**Comment by pschatzmann** [comment]
If you mean an example for a Bluetooth sink, just look at the first example in this project!

**Comment by chamatkari-hub** [comment]
How to change the i2s config and pin config?

**Comment by pschatzmann** [comment]
I't described in the Readme as well and in the [Wiki](https://github.com/pschatzmann/arduino-audio-tools/wiki/External-DAC)

**Comment by chamatkari-hub** [comment]
![Screenshot 2024-10-08 155942](https://github.com/user-attachments/assets/4726229d-6222-4e97-a0e2-ff7316749234)
Just this much of code taking whole space...how?

**Comment by pschatzmann** [comment]
This has been answered in the FAQ!
Set a proper partition scheme...

**Comment by chamatkari-hub** [comment]
Where is the FAQ section please provide me a link for it

**Comment by pschatzmann** [comment]
The first line in the Wiki

**Comment by chamatkari-hub** [comment]
Just that of code is taking 60% of the storage when I'm selecting the partition scheme as Huge app I have a long program left how to manage all of that together?

**Comment by chamatkari-hub** [comment]
![image](https://github.com/user-attachments/assets/c47a714f-3667-481c-8535-767e49937f43)

**Comment by chamatkari-hub** [comment]
Is there any way possible that i can turn off the a2dp broadcast without turning off the Bluetooth serial?

**Comment by chamatkari-hub** [comment]
decoder.begin(); , ive used this in the setup section but after that if I am starting the a2dp sync then the device isn't connecting to it..please help

**Comment by pschatzmann** [comment]
https://github.com/pschatzmann/arduino-audio-tools/wiki/It's-not-working

**Comment by chamatkari-hub** [comment]
Do you have any example for it to handle a2dp sync and SD together? Or can you please give a small reference code for it?
