### ISSUE TITLE
ES8388 seldomly changes volume when pause-->play

### ISSUE THREAD

**Issue by Erklei** [pschatzmann/ESP32-A2DP#619]
### Problem Description

In this case Android 13, but it may not be important: 

- Start playing music in Spotify etc.
- Put to pause
- Wait till [BluetoothA2DPOutput.cpp:255] set_output_active(): [BT_AV] i2s_stop appears to log
- Press play

Now in some cases the board volume is lowered.

### Device Description

ESP32-WROOM-32E

### Sketch

```cpp

#include "AudioTools.h"
#include "AudioTools/AudioLibs/AudioBoardStream.h"  
#include "BluetoothA2DPSink.h"                     
#include "AudioBoard.h"


DriverPins my_pins;
AudioBoard board(AudioDriverES8388, my_pins);

#define pinI2S_MSCK 0
#define pinI2S_BSCK 27  /* Audio data bit clock */
#define pinI2S_WS 25    /* Audio data left and right clock */
#define pinI2S_SDOUT 26 /* ESP32 audio data output (to speakers) */
#define pinI2S_I2C_SCL 15
#define pinI2S_I2C_SDA 4

#define pinBT_UART_TX 33
#define pinBT_UART_RX 13

AudioBoardStream kit(board);  //(AudioKitEs8388V1)
BluetoothA2DPSink a2dp_sink(kit);


void setup() {
  LOGLEVEL_AUDIODRIVER = AudioDriverWarning;  //AudioDriverInfo;
  Serial.begin(115200);
  Serial1.begin(4800, SERIAL_8N1, pinBT_UART_RX, pinBT_UART_TX);
  gpio_pullup_dis(GPIO_NUM_13);  

  // add i2c codec pins: scl, sda, port
  my_pins.addI2C(PinFunction::CODEC, pinI2S_I2C_SCL, pinI2S_I2C_SDA, 0x20);
  // add i2s pins: mclk, bclk, ws, data_out, data_in
  my_pins.addI2S(PinFunction::CODEC, pinI2S_MSCK, pinI2S_BSCK, pinI2S_WS, pinI2S_SDOUT, 0);

  // configure codec
  CodecConfig cfg;
  cfg.input_device = ADC_INPUT_LINE1;
  cfg.output_device = DAC_OUTPUT_ALL;
  cfg.i2s.bits = BIT_LENGTH_16BITS;
  cfg.i2s.rate = RATE_44K;
  //cfg.i2s.fmt = I2S_NORMAL;
  //cfg.i2s.mode = MODE_SLAVE;
  board.begin(cfg);
    a2dp_sink.set_auto_reconnect(true);
  a2dp_sink.start("Vol test");
  kit.setVolume(0.9);  //1.0 max 
}


void loop() {
  static uint32_t Dbg_timer;
 
  if ((millis() - Dbg_timer) > 1000) {
    Dbg_timer = millis();
    if (kit.getVolume() < 0.8) {
      Serial.printf("Kit vol: %f, sink vol %d \n", kit.getVolume(), a2dp_sink.get_volume());
      kit.setVolume(0.9);
      Serial.printf("Kit vol: %f, sink vol %d \n", kit.getVolume(), a2dp_sink.get_volume());
    }
  }

  delay(10);  // do nothing
}
```

### Other Steps to Reproduce

Log output:
[ 28211][W][BluetoothA2DPOutput.cpp:255] set_output_active(): [BT_AV] i2s_stop
[ 30927][W][Wire.cpp:296] begin(): Bus already started in Master Mode.
Kit vol: 0.660000, sink vol 127 
Kit vol: 0.870000, sink vol 127 
[ 40668][W][BluetoothA2DPOutput.cpp:255] set_output_active(): [BT_AV] i2s_stop
[ 48570][W][Wire.cpp:296] begin(): Bus already started in Master Mode.
[ 48598][W][BluetoothA2DPSink.cpp:1234] i2s_write_data(): [BT_AV] i2s_write_data failed - inactive
Kit vol: 0.660000, sink vol 127 
Kit vol: 0.870000, sink vol 127 
[ 57798][W][BluetoothA2DPOutput.cpp:255] set_output_active(): [BT_AV] i2s_stop
[ 59542][W][Wire.cpp:296] begin(): Bus already started in Master Mode.
Kit vol: 0.660000, sink vol 127 
Kit vol: 0.870000, sink vol 127 
[ 86286][W][BluetoothA2DPOutput.cpp:255] set_output_active(): [BT_AV] i2s_stop
[ 86652][W][Wire.cpp:296] begin(): Bus already started in Master Mode.
Kit vol: 0.660000, sink vol 127 
Kit vol: 0.870000, sink vol 127 

### Provide your Version of the EP32 Arduino Core (or the IDF Version)

ESP32 3.1.0, other libraries downloaded last week from here

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
I could reproduce your issue and have committed a [correction to the AudioTools](https://github.com/pschatzmann/arduino-audio-tools/commit/96d4788c91d7b7356fc83f96511ad8aee5ffed92).

When you install the latest master branch, the issue should be resolved....
