### ISSUE TITLE
from max98357 audio data to a2dp_source bluetooth headset

### ISSUE THREAD

**Issue by fmkkaya** [pschatzmann/ESP32-A2DP#630]
### Problem Description

Hello,
I use the audio library with max98357 and transmit the sound to the speaker with i2s. Is it possible to transmit the data in i2s to bluetooth with the BluetoothA2DPSource library. when I examined your library, I could not see it. does your library support this? would you consider adding it?

### Device Description

Esp32-wroom arduino

### Sketch

```cpp
a2dp_source.start("Galaxy Buds+ (D504)", get_sound_data_from_i2s);
```

### Provide your Version of the EP32 Arduino Core (or the IDF Version)

2.0.14

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
There are plenty of [examples in the AudioTools library](https://github.com/pschatzmann/arduino-audio-tools/tree/main/examples/examples-communication/a2dp)

**Comment by pschatzmann** [comment]
library ? I think you were looking for a sketch from I2S to A2DP. So that would be

- basic-i2s-a2dp
- stream-i2s-a2dp
