### ISSUE TITLE
How to Get Audio Active Status

### ISSUE THREAD

**Issue by hotteshen** [pschatzmann/ESP32-A2DP#72]
I am using this library for audio visualization.
When there's no output, my amplifier still has small noise on the output.
So the visualizer displays animation when no audio is streamed via Bluetooth.

How to know the audio active status?

I thought to use play/pause control status. But there are other effect sounds of touch actions when the music is not.
Is there a simple way to get such status?
Like this,
```a2dp.is_audio_active()```

**Comment by pschatzmann** [comment]
see https://pschatzmann.github.io/ESP32-A2DP/html/class_bluetooth_a2_d_p_sink.html

get_audio_state () might help…

**Comment by hotteshen** [comment]
Exactly whar I wanted.
Thank you!
