### ISSUE TITLE
A parameter to explicitly set MONO/STEREO in i2s_config 

### ISSUE THREAD

**Issue by jordancrubin** [pschatzmann/ESP32-A2DP#76]
Attempting to stay with the config format provided, I see the following in i2S_channel_t but do not see this within i2S_config to be evoked with the other default params

typedef enum {
    I2S_CHANNEL_MONO        = 1,            /*!< I2S 1 channel (mono)*/
    I2S_CHANNEL_STEREO      = 2             /*!< I2S 2 channel (stereo)*/
} i2s_channel_t;

        // setup default i2s config
        i2s_config = {
            .mode = (i2s_mode_t) (I2S_MODE_MASTER | I2S_MODE_TX),
            .sample_rate = 44100,
            .bits_per_sample = (i2s_bits_per_sample_t)16,
            .channel_format = I2S_CHANNEL_FMT_RIGHT_LEFT,
            .communication_format = (i2s_comm_format_t) (I2S_COMM_FORMAT_STAND_I2S),
            .intr_alloc_flags = 0, // default interrupt priority
            .dma_buf_count = 8,
            .dma_buf_len = 64,
            .use_apll = false,
            .tx_desc_auto_clear = true // avoiding noise in case of data unavailability
        };

Perhaps Im just going about this the wrong way?

**Comment by pschatzmann** [comment]
I have added the method set_channels (i2s_channel_t channels) to the BluetoothA2DPSink
