### ISSUE TITLE
Trying to connect 24-bit PCM5102 PCM5102A Stereo

### ISSUE THREAD

**Issue by podaen** [pschatzmann/ESP32-A2DP#84]
I am stuck on this. I don't understand how to connect the board below. On the side of the esp32 is clear, but on the external dac SD, L/R, WS can not be found on the board. Also the BCK is in the colume ESP32. Could you please check this again. 

[External Dac 24-bit PCM5102 PCM5102A Stereo](https://github.com/pschatzmann/ESP32-A2DP/wiki/External-DAC#24-bit-pcm5102-pcm5102a-stereo-dac-digital-to-analog-converter-pll-voice-module-phat)

**Comment by pschatzmann** [comment]
I updated the documentation can you try it out and let me know the results ?

**Comment by podaen** [comment]
Thanks, that should do it. Only one thing you named XMT as XST.

**Comment by pschatzmann** [comment]
corrected as well. Thanks for your feed back....

**Comment by podaen** [comment]
Can it be that L/R to GND is gone?

**Comment by podaen** [comment]
I found this [connection diagram for a raspberry pi.](https://goteborgsaventyrscenter.se/product/mevjpym68n31/i2s-pcm5102-dac-decoder-32-bit-player-module-than-es9023-pcm1794-for-raspberry-pi)

As you can see the FTL,DMP,SCL and FMT are connected to ground.

**Comment by pschatzmann** [comment]
If I remember right, out of these only FMT is critical. I guess the others are connected to ground to have a defined state.
For DMP and FLT you could play around if setting it to high improves the quality.
I was really struggeling with this module and only when I started to set XMT to high it started to work for me.

**Comment by podaen** [comment]
I diden't test it yet. I let you know. I am trying to compile without disable the warnings. But without succes for now.

**Comment by pschatzmann** [comment]
I hope the warnings are not coming from my library. 
If so are you using the latest version ?

**Comment by podaen** [comment]
I downloaded them a while a go. The 4th of may to be precese. Are they addapted?

**Comment by podaen** [comment]
oh yes, I see now. Thanks

**Comment by pschatzmann** [comment]
You might even consider to upgrade the ESP32 release to 2.0.0

**Comment by podaen** [comment]
What do you mean by upgrading the ESP32 release? Updating the boards of Arduino IDE?

The board works with you suggested wiring!  

I just get noise when there is no music playing, even when the ESP32 is not powered on... Soo I think it is coming from my bad power supply I am currently using. The wiring is not solderd yet and the two GND of the power supply are currently not connected to each other. I will try it with my lineare regulated power supply. Would it help by setting the XSMT to low... This is what the datasheet tells me: Soft mute control : Soft mute (Low) / soft un-mute (High).

**Comment by podaen** [comment]
I did the following...

a2dp_sink.set_volume(0);

digitalWrite(PinMute,LOW);

Bound the grounds together

The noise remains. The only thing I can do as far as I know is place a filter around the power supply cable. Or use an other powersupply and solder the wires.

**Comment by podaen** [comment]
Is the sound muted when it's not connected?

**Comment by pschatzmann** [comment]
In my code, the disconnect event is switching off I2S. 
The only other setting related to noise that I am aware of is in  

            i2s_config.tx_desc_auto_clear = true // avoiding noise in case of data unavailability

**Comment by podaen** [comment]
> You might even consider to upgrade the ESP32 release to 2.0.0

You where right, there was a new release.

I followed the instruction

[instruction](https://support.arduino.cc/hc/en-us/articles/360016119519-How-to-add-boards-in-the-board-manager)
