### ISSUE TITLE
Volume issue

### ISSUE THREAD

**Issue by Alfred586** [pschatzmann/ESP32-A2DP#88]
Thankyou Phil for your excellent work.

I found an issue in the volume control.
When i change the volume in the source side (smartphone), there's no change in the sink side, always is the maximum volume, the previous version did not have that issue.

Code: bt_music_receiver_simple
Library version: 1.4.0
ESP32 2.0.0 arduino core

**Comment by Alfred586** [comment]
I don't know how to make a pull request, so i decided to write what i found here, sorry.
I found that the flag "is_volume_used" is not been activated in the function "void BluetoothA2DPSink::volume_set_by_controller(uint8_t volume)".
If i put the flag in these function, the issue is corrected succesfully.
I made this correction in the file "BluetoothA2DPSink.cpp".

**Comment by pschatzmann** [comment]
Thanks for your input. I have committed the correction. 
Can you double check and let me know if it is ok now ?

**Comment by Alfred586** [comment]
Yes, now works perfect.
Thanks.
I will close de issue.
