### ISSUE TITLE
Add Output to "simulated" DAC

### ISSUE THREAD

**Issue by DrNeuroSurg** [pschatzmann/ESP32-A2DP#91]
After a (long) look at https://github.com/earlephilhower/ESP8266Audio , I think it would possible and a great option to make output as Sigma-Delata modulation, isn't it ? 
Take look in the above source ("AudioOutputI2SNoDAC.h + .cpp").
So one could use this library to build a very cheap BT "speaker" with only one transistor an only one resistor !

**Comment by pschatzmann** [comment]
What would be the advantages of this compared to directly using the built in "internal DAC" of the ESP32 ?

**Comment by DrNeuroSurg** [comment]
IMHO if you feed the output over a simple low-pass (RC) and/or a transistor (for driving a speaker) this should give a much more better sound than the 8-bit DAC - isn‘t it ?

**Comment by pschatzmann** [comment]
I honestly don't know and I guess this would be worth an experiment. Do you have the necessary components ?

**Comment by DrNeuroSurg** [comment]
The components aren't the problem :-( 
tried the example from "AudioOutputI2SNoDAC" and it looks (so far) fine .. Now I'm on the algorithm itself ..

**Comment by pschatzmann** [comment]
Did you manage to integrate the logic from AudioOutputI2SNoDAC or do you need some help ?

**Comment by DrNeuroSurg** [comment]
Sorry - I think, it‘s not worth the effort:
So if you convert the 8bit (where you can have 256 different values - you know ?) and you make a DeltaSigma value of that, you‘ll need (at least) 128bit … to achieve the same resolution, for the price of noise ..
