### ISSUE TITLE
functions to connect/disconnect/check if connected

### ISSUE THREAD

**Issue by NoMedia-py** [pschatzmann/ESP32-A2DP#92]
How can functions be implemented for connecting/disconnecting the BlootoothA2DSink to/from deveices?
How can i check if an device is connected to the sink?

**Comment by pschatzmann** [comment]
I propose that you have a look at the examples and the documentation 
https://pschatzmann.github.io/ESP32-A2DP/html/class_bluetooth_a2_d_p_sink.html
