### ISSUE TITLE
Writing incoming A2DP sink data stream to a wav file

### ISSUE THREAD

**Issue by akash-phadtare** [pschatzmann/ESP32-A2DP#96]
Hello!

In the following function, what would be the best way to save the data stream to a wav file? I tried writing the bytes directly to a wav file and it did not work. Would appreciate if you can point me to the right direction, also don't mind contributing that as a feature to this project if it ends up working. 

void read_data_stream(const uint8_t *data, uint32_t length)
{
  // Do something with the data packet
}

Thanks and regards,
Akash

**Comment by pschatzmann** [comment]
I propose that you have a look at https://github.com/pschatzmann/arduino-audio-tools.
There you can find different encoders: E.g. https://pschatzmann.github.io/arduino-audio-tools/html/classaudio__tools_1_1_audio_encoder.html
