### ISSUE TITLE
Isn't working with TinyPICO with mono DAC output.

### ISSUE THREAD

**Issue by olsonap** [pschatzmann/ESP32-A2DP#98]
As the header describes, I'm trying to use this on a TinyPICO (ESP32-PICO-D4) with the TinyPICO Audio Shield.
The TinyPICO Audio Shield only uses one of the two DAC outputs, so it is a mono amplifier.
I don't know if that has anything to do with why this isn't working, but I'm getting no audio. The only thing I can hear is crackling which does not correspond to the audio I'm trying to play at all. The device does show up and connect on my phone.

To be clear, I'm only trying to use the provided example with internal DAC output. I tried the I2S example as well just for kicks, and in that case, I was able to hear a difference when audio was paused and unpaused, but it is still (obviously in this case) just static.

**Comment by olsonap** [comment]
For added clarity, the DAC pin in use is Pin 25.

**Comment by olsonap** [comment]
https://github.com/pschatzmann/ESP32-A2DP/issues/76
I see you addressed mono in the issue above but I'm afraid I don't know how to implement your method. Could you provide an example? Perhaps of how it would be added to your bt_music_receiver_to_dac example?

**Comment by pschatzmann** [comment]
I suggest to split up the problem and to 

- try to figure out if my library works:  just use the the bt_music_receiver_to_dac example and test with some earphones using GND and GPIO25 or GPIO26. 
![Earphones](https://pschatzmann.github.io/arduino-audio-tools/resources/earphones.jpg)

- audio shield: As far as I can see the TinyPICO Audio Shield  is not using I2S but it's own audio interface. So you would need to provide your own implementation by getting the data as described in 'Accessing the Sink Data Stream with Callbacks'

**Comment by pschatzmann** [comment]
I also would suggest to set the Core Debug Level setting to Verbose just to get more logging info

**Comment by pschatzmann** [comment]
I think I have it working again: the communication format needs to be I2S_COMM_FORMAT_STAND_MSB
The corrections have been committed to the main branch...

**Comment by olsonap** [comment]
I tried it. I can definitely hear the audio deep in the background for the first time but it's overpowered by a sin wave like beeping sound (difficult to explain).
